// This file is generated by tool/generate_icons.py.
// Do not edit by hand.

import 'package:flutter/widgets.dart';

const String _kGravityIconsFontFamily = 'GravityIcons';
const String _kGravityIconsFontPackage = 'flutty_gravity_icons';

/// A single Gravity icon glyph.
@immutable
class GravityIcon extends IconData {
  /// Creates a Gravity icon from a font [codePoint].
  const GravityIcon(super.codePoint)
    : super(
        fontFamily: _kGravityIconsFontFamily,
        fontPackage: _kGravityIconsFontPackage,
      );
}

/// The complete Gravity Icons collection.
///
/// Example:
/// ```dart
/// Icon(GravityIcons.heart);
/// Icon(GravityIcons.heartFill);
/// ```
abstract final class GravityIcons {
  GravityIcons._();

  /// The number of glyphs bundled in this package.
  static const int count = 781;

  /// `Icon(GravityIcons.abbrApi)`.
  static const GravityIcon abbrApi = GravityIcon(0xf40d);

  /// `Icon(GravityIcons.abbrMl)`.
  static const GravityIcon abbrMl = GravityIcon(0xf40c);

  /// `Icon(GravityIcons.abbrQl)`.
  static const GravityIcon abbrQl = GravityIcon(0xf40b);

  /// `Icon(GravityIcons.abbrSql)`.
  static const GravityIcon abbrSql = GravityIcon(0xf40a);

  /// `Icon(GravityIcons.abbrZip)`.
  static const GravityIcon abbrZip = GravityIcon(0xf409);

  /// `Icon(GravityIcons.alarm)`.
  static const GravityIcon alarm = GravityIcon(0xf407);

  /// `Icon(GravityIcons.alarmFill)`.
  static const GravityIcon alarmFill = GravityIcon(0xf408);

  /// `Icon(GravityIcons.almostEqual)`.
  static const GravityIcon almostEqual = GravityIcon(0xf406);

  /// `Icon(GravityIcons.antennaSignal)`.
  static const GravityIcon antennaSignal = GravityIcon(0xf405);

  /// `Icon(GravityIcons.aperture)`.
  static const GravityIcon aperture = GravityIcon(0xf404);

  /// `Icon(GravityIcons.archive)`.
  static const GravityIcon archive = GravityIcon(0xf403);

  /// `Icon(GravityIcons.arrowChevronDown)`.
  static const GravityIcon arrowChevronDown = GravityIcon(0xf402);

  /// `Icon(GravityIcons.arrowChevronLeft)`.
  static const GravityIcon arrowChevronLeft = GravityIcon(0xf401);

  /// `Icon(GravityIcons.arrowChevronRight)`.
  static const GravityIcon arrowChevronRight = GravityIcon(0xf400);

  /// `Icon(GravityIcons.arrowChevronUp)`.
  static const GravityIcon arrowChevronUp = GravityIcon(0xf3ff);

  /// `Icon(GravityIcons.arrowDown)`.
  static const GravityIcon arrowDown = GravityIcon(0xf3f9);

  /// `Icon(GravityIcons.arrowDownFromLine)`.
  static const GravityIcon arrowDownFromLine = GravityIcon(0xf3fe);

  /// `Icon(GravityIcons.arrowDownLeft)`.
  static const GravityIcon arrowDownLeft = GravityIcon(0xf3fd);

  /// `Icon(GravityIcons.arrowDownRight)`.
  static const GravityIcon arrowDownRight = GravityIcon(0xf3fc);

  /// `Icon(GravityIcons.arrowDownToLine)`.
  static const GravityIcon arrowDownToLine = GravityIcon(0xf3fb);

  /// `Icon(GravityIcons.arrowDownToSquare)`.
  static const GravityIcon arrowDownToSquare = GravityIcon(0xf3fa);

  /// `Icon(GravityIcons.arrowLeft)`.
  static const GravityIcon arrowLeft = GravityIcon(0xf3f6);

  /// `Icon(GravityIcons.arrowLeftFromLine)`.
  static const GravityIcon arrowLeftFromLine = GravityIcon(0xf3f8);

  /// `Icon(GravityIcons.arrowLeftToLine)`.
  static const GravityIcon arrowLeftToLine = GravityIcon(0xf3f7);

  /// `Icon(GravityIcons.arrowRight)`.
  static const GravityIcon arrowRight = GravityIcon(0xf3f0);

  /// `Icon(GravityIcons.arrowRightArrowLeft)`.
  static const GravityIcon arrowRightArrowLeft = GravityIcon(0xf3f5);

  /// `Icon(GravityIcons.arrowRightFromLine)`.
  static const GravityIcon arrowRightFromLine = GravityIcon(0xf3f4);

  /// `Icon(GravityIcons.arrowRightFromSquare)`.
  static const GravityIcon arrowRightFromSquare = GravityIcon(0xf3f3);

  /// `Icon(GravityIcons.arrowRightToLine)`.
  static const GravityIcon arrowRightToLine = GravityIcon(0xf3f2);

  /// `Icon(GravityIcons.arrowRightToSquare)`.
  static const GravityIcon arrowRightToSquare = GravityIcon(0xf3f1);

  /// `Icon(GravityIcons.arrowRotateLeft)`.
  static const GravityIcon arrowRotateLeft = GravityIcon(0xf3ee);

  /// `Icon(GravityIcons.arrowRotateLeftNumber5)`.
  static const GravityIcon arrowRotateLeftNumber5 = GravityIcon(0xf3ef);

  /// `Icon(GravityIcons.arrowRotateRight)`.
  static const GravityIcon arrowRotateRight = GravityIcon(0xf3ec);

  /// `Icon(GravityIcons.arrowRotateRightNumber5)`.
  static const GravityIcon arrowRotateRightNumber5 = GravityIcon(0xf3ed);

  /// `Icon(GravityIcons.arrowShapeDown)`.
  static const GravityIcon arrowShapeDown = GravityIcon(0xf3e9);

  /// `Icon(GravityIcons.arrowShapeDownFromLine)`.
  static const GravityIcon arrowShapeDownFromLine = GravityIcon(0xf3eb);

  /// `Icon(GravityIcons.arrowShapeDownToLine)`.
  static const GravityIcon arrowShapeDownToLine = GravityIcon(0xf3ea);

  /// `Icon(GravityIcons.arrowShapeLeft)`.
  static const GravityIcon arrowShapeLeft = GravityIcon(0xf3e6);

  /// `Icon(GravityIcons.arrowShapeLeftFromLine)`.
  static const GravityIcon arrowShapeLeftFromLine = GravityIcon(0xf3e8);

  /// `Icon(GravityIcons.arrowShapeLeftToLine)`.
  static const GravityIcon arrowShapeLeftToLine = GravityIcon(0xf3e7);

  /// `Icon(GravityIcons.arrowShapeRight)`.
  static const GravityIcon arrowShapeRight = GravityIcon(0xf3e3);

  /// `Icon(GravityIcons.arrowShapeRightFromLine)`.
  static const GravityIcon arrowShapeRightFromLine = GravityIcon(0xf3e5);

  /// `Icon(GravityIcons.arrowShapeRightToLine)`.
  static const GravityIcon arrowShapeRightToLine = GravityIcon(0xf3e4);

  /// `Icon(GravityIcons.arrowShapeTurnUpLeft)`.
  static const GravityIcon arrowShapeTurnUpLeft = GravityIcon(0xf3e2);

  /// `Icon(GravityIcons.arrowShapeTurnUpRight)`.
  static const GravityIcon arrowShapeTurnUpRight = GravityIcon(0xf3e1);

  /// `Icon(GravityIcons.arrowShapeUp)`.
  static const GravityIcon arrowShapeUp = GravityIcon(0xf3de);

  /// `Icon(GravityIcons.arrowShapeUpFromLine)`.
  static const GravityIcon arrowShapeUpFromLine = GravityIcon(0xf3e0);

  /// `Icon(GravityIcons.arrowShapeUpToLine)`.
  static const GravityIcon arrowShapeUpToLine = GravityIcon(0xf3df);

  /// `Icon(GravityIcons.arrowUp)`.
  static const GravityIcon arrowUp = GravityIcon(0xf3d5);

  /// `Icon(GravityIcons.arrowUpArrowDown)`.
  static const GravityIcon arrowUpArrowDown = GravityIcon(0xf3dd);

  /// `Icon(GravityIcons.arrowUpFromLine)`.
  static const GravityIcon arrowUpFromLine = GravityIcon(0xf3dc);

  /// `Icon(GravityIcons.arrowUpFromSquare)`.
  static const GravityIcon arrowUpFromSquare = GravityIcon(0xf3da);

  /// `Icon(GravityIcons.arrowUpFromSquareSlash)`.
  static const GravityIcon arrowUpFromSquareSlash = GravityIcon(0xf3db);

  /// `Icon(GravityIcons.arrowUpLeft)`.
  static const GravityIcon arrowUpLeft = GravityIcon(0xf3d9);

  /// `Icon(GravityIcons.arrowUpRight)`.
  static const GravityIcon arrowUpRight = GravityIcon(0xf3d7);

  /// `Icon(GravityIcons.arrowUpRightFromSquare)`.
  static const GravityIcon arrowUpRightFromSquare = GravityIcon(0xf3d8);

  /// `Icon(GravityIcons.arrowUpToLine)`.
  static const GravityIcon arrowUpToLine = GravityIcon(0xf3d6);

  /// `Icon(GravityIcons.arrowUturnCcwDown)`.
  static const GravityIcon arrowUturnCcwDown = GravityIcon(0xf3d4);

  /// `Icon(GravityIcons.arrowUturnCcwLeft)`.
  static const GravityIcon arrowUturnCcwLeft = GravityIcon(0xf3d3);

  /// `Icon(GravityIcons.arrowUturnCcwRight)`.
  static const GravityIcon arrowUturnCcwRight = GravityIcon(0xf3d2);

  /// `Icon(GravityIcons.arrowUturnCwDown)`.
  static const GravityIcon arrowUturnCwDown = GravityIcon(0xf3d1);

  /// `Icon(GravityIcons.arrowUturnCwLeft)`.
  static const GravityIcon arrowUturnCwLeft = GravityIcon(0xf3d0);

  /// `Icon(GravityIcons.arrowUturnCwRight)`.
  static const GravityIcon arrowUturnCwRight = GravityIcon(0xf3cf);

  /// `Icon(GravityIcons.arrows3RotateLeft)`.
  static const GravityIcon arrows3RotateLeft = GravityIcon(0xf3cd);

  /// `Icon(GravityIcons.arrows3RotateLeftLetterA)`.
  static const GravityIcon arrows3RotateLeftLetterA = GravityIcon(0xf3ce);

  /// `Icon(GravityIcons.arrows3RotateRight)`.
  static const GravityIcon arrows3RotateRight = GravityIcon(0xf3cc);

  /// `Icon(GravityIcons.arrowsExpand)`.
  static const GravityIcon arrowsExpand = GravityIcon(0xf3c9);

  /// `Icon(GravityIcons.arrowsExpandHorizontal)`.
  static const GravityIcon arrowsExpandHorizontal = GravityIcon(0xf3cb);

  /// `Icon(GravityIcons.arrowsExpandVertical)`.
  static const GravityIcon arrowsExpandVertical = GravityIcon(0xf3ca);

  /// `Icon(GravityIcons.arrowsOppositeToDots)`.
  static const GravityIcon arrowsOppositeToDots = GravityIcon(0xf3c8);

  /// `Icon(GravityIcons.arrowsRotateLeft)`.
  static const GravityIcon arrowsRotateLeft = GravityIcon(0xf3c6);

  /// `Icon(GravityIcons.arrowsRotateLeftSlash)`.
  static const GravityIcon arrowsRotateLeftSlash = GravityIcon(0xf3c7);

  /// `Icon(GravityIcons.arrowsRotateRight)`.
  static const GravityIcon arrowsRotateRight = GravityIcon(0xf3c4);

  /// `Icon(GravityIcons.arrowsRotateRightSlash)`.
  static const GravityIcon arrowsRotateRightSlash = GravityIcon(0xf3c5);

  /// `Icon(GravityIcons.at)`.
  static const GravityIcon at = GravityIcon(0xf3c3);

  /// `Icon(GravityIcons.backwardStep)`.
  static const GravityIcon backwardStep = GravityIcon(0xf3c1);

  /// `Icon(GravityIcons.backwardStepFill)`.
  static const GravityIcon backwardStepFill = GravityIcon(0xf3c2);

  /// `Icon(GravityIcons.ban)`.
  static const GravityIcon ban = GravityIcon(0xf3c0);

  /// `Icon(GravityIcons.bars)`.
  static const GravityIcon bars = GravityIcon(0xf3b3);

  /// `Icon(GravityIcons.barsAscendingAlignCenter)`.
  static const GravityIcon barsAscendingAlignCenter = GravityIcon(0xf3bf);

  /// `Icon(GravityIcons.barsAscendingAlignLeft)`.
  static const GravityIcon barsAscendingAlignLeft = GravityIcon(0xf3bc);

  /// `Icon(GravityIcons.barsAscendingAlignLeftArrowDown)`.
  static const GravityIcon barsAscendingAlignLeftArrowDown = GravityIcon(
    0xf3be,
  );

  /// `Icon(GravityIcons.barsAscendingAlignLeftArrowUp)`.
  static const GravityIcon barsAscendingAlignLeftArrowUp = GravityIcon(0xf3bd);

  /// `Icon(GravityIcons.barsAscendingAlignRight)`.
  static const GravityIcon barsAscendingAlignRight = GravityIcon(0xf3bb);

  /// `Icon(GravityIcons.barsDescendingAlignCenter)`.
  static const GravityIcon barsDescendingAlignCenter = GravityIcon(0xf3ba);

  /// `Icon(GravityIcons.barsDescendingAlignLeft)`.
  static const GravityIcon barsDescendingAlignLeft = GravityIcon(0xf3b7);

  /// `Icon(GravityIcons.barsDescendingAlignLeftArrowDown)`.
  static const GravityIcon barsDescendingAlignLeftArrowDown = GravityIcon(
    0xf3b9,
  );

  /// `Icon(GravityIcons.barsDescendingAlignLeftArrowUp)`.
  static const GravityIcon barsDescendingAlignLeftArrowUp = GravityIcon(0xf3b8);

  /// `Icon(GravityIcons.barsDescendingAlignRight)`.
  static const GravityIcon barsDescendingAlignRight = GravityIcon(0xf3b6);

  /// `Icon(GravityIcons.barsPlay)`.
  static const GravityIcon barsPlay = GravityIcon(0xf3b5);

  /// `Icon(GravityIcons.barsUnaligned)`.
  static const GravityIcon barsUnaligned = GravityIcon(0xf3b4);

  /// `Icon(GravityIcons.bell)`.
  static const GravityIcon bell = GravityIcon(0xf3af);

  /// `Icon(GravityIcons.bellDot)`.
  static const GravityIcon bellDot = GravityIcon(0xf3b2);

  /// `Icon(GravityIcons.bellFill)`.
  static const GravityIcon bellFill = GravityIcon(0xf3b1);

  /// `Icon(GravityIcons.bellSlash)`.
  static const GravityIcon bellSlash = GravityIcon(0xf3b0);

  /// `Icon(GravityIcons.binoculars)`.
  static const GravityIcon binoculars = GravityIcon(0xf3ae);

  /// `Icon(GravityIcons.bold)`.
  static const GravityIcon bold = GravityIcon(0xf3ad);

  /// `Icon(GravityIcons.book)`.
  static const GravityIcon book = GravityIcon(0xf3ab);

  /// `Icon(GravityIcons.bookOpen)`.
  static const GravityIcon bookOpen = GravityIcon(0xf3ac);

  /// `Icon(GravityIcons.bookmark)`.
  static const GravityIcon bookmark = GravityIcon(0xf3a9);

  /// `Icon(GravityIcons.bookmarkFill)`.
  static const GravityIcon bookmarkFill = GravityIcon(0xf3aa);

  /// `Icon(GravityIcons.books)`.
  static const GravityIcon books = GravityIcon(0xf3a8);

  /// `Icon(GravityIcons.box)`.
  static const GravityIcon box = GravityIcon(0xf3a7);

  /// `Icon(GravityIcons.boxes3)`.
  static const GravityIcon boxes3 = GravityIcon(0xf3a6);

  /// `Icon(GravityIcons.branchesDown)`.
  static const GravityIcon branchesDown = GravityIcon(0xf3a5);

  /// `Icon(GravityIcons.branchesRight)`.
  static const GravityIcon branchesRight = GravityIcon(0xf3a3);

  /// `Icon(GravityIcons.branchesRightArrowRight)`.
  static const GravityIcon branchesRightArrowRight = GravityIcon(0xf3a4);

  /// `Icon(GravityIcons.briefcase)`.
  static const GravityIcon briefcase = GravityIcon(0xf3a1);

  /// `Icon(GravityIcons.briefcaseFill)`.
  static const GravityIcon briefcaseFill = GravityIcon(0xf3a2);

  /// `Icon(GravityIcons.broadcastSignal)`.
  static const GravityIcon broadcastSignal = GravityIcon(0xf3a0);

  /// `Icon(GravityIcons.broomMotion)`.
  static const GravityIcon broomMotion = GravityIcon(0xf39e);

  /// `Icon(GravityIcons.broomMotionFill)`.
  static const GravityIcon broomMotionFill = GravityIcon(0xf39f);

  /// `Icon(GravityIcons.brush)`.
  static const GravityIcon brush = GravityIcon(0xf39d);

  /// `Icon(GravityIcons.bucket)`.
  static const GravityIcon bucket = GravityIcon(0xf39b);

  /// `Icon(GravityIcons.bucketPaint)`.
  static const GravityIcon bucketPaint = GravityIcon(0xf39c);

  /// `Icon(GravityIcons.bug)`.
  static const GravityIcon bug = GravityIcon(0xf39a);

  /// `Icon(GravityIcons.bulb)`.
  static const GravityIcon bulb = GravityIcon(0xf399);

  /// `Icon(GravityIcons.calculator)`.
  static const GravityIcon calculator = GravityIcon(0xf398);

  /// `Icon(GravityIcons.calendar)`.
  static const GravityIcon calendar = GravityIcon(0xf396);

  /// `Icon(GravityIcons.calendarXmark)`.
  static const GravityIcon calendarXmark = GravityIcon(0xf397);

  /// `Icon(GravityIcons.camera)`.
  static const GravityIcon camera = GravityIcon(0xf395);

  /// `Icon(GravityIcons.car)`.
  static const GravityIcon car = GravityIcon(0xf394);

  /// `Icon(GravityIcons.cardClub)`.
  static const GravityIcon cardClub = GravityIcon(0xf393);

  /// `Icon(GravityIcons.cardDiamond)`.
  static const GravityIcon cardDiamond = GravityIcon(0xf392);

  /// `Icon(GravityIcons.cardHeart)`.
  static const GravityIcon cardHeart = GravityIcon(0xf391);

  /// `Icon(GravityIcons.cardSpade)`.
  static const GravityIcon cardSpade = GravityIcon(0xf390);

  /// `Icon(GravityIcons.caretDown)`.
  static const GravityIcon caretDown = GravityIcon(0xf38f);

  /// `Icon(GravityIcons.caretLeft)`.
  static const GravityIcon caretLeft = GravityIcon(0xf38e);

  /// `Icon(GravityIcons.caretRight)`.
  static const GravityIcon caretRight = GravityIcon(0xf38d);

  /// `Icon(GravityIcons.caretUp)`.
  static const GravityIcon caretUp = GravityIcon(0xf38c);

  /// `Icon(GravityIcons.caretsExpandVertical)`.
  static const GravityIcon caretsExpandVertical = GravityIcon(0xf38b);

  /// `Icon(GravityIcons.chartAreaStacked)`.
  static const GravityIcon chartAreaStacked = GravityIcon(0xf389);

  /// `Icon(GravityIcons.chartAreaStackedNormalized)`.
  static const GravityIcon chartAreaStackedNormalized = GravityIcon(0xf38a);

  /// `Icon(GravityIcons.chartBar)`.
  static const GravityIcon chartBar = GravityIcon(0xf387);

  /// `Icon(GravityIcons.chartBarStacked)`.
  static const GravityIcon chartBarStacked = GravityIcon(0xf388);

  /// `Icon(GravityIcons.chartColumn)`.
  static const GravityIcon chartColumn = GravityIcon(0xf385);

  /// `Icon(GravityIcons.chartColumnStacked)`.
  static const GravityIcon chartColumnStacked = GravityIcon(0xf386);

  /// `Icon(GravityIcons.chartDonut)`.
  static const GravityIcon chartDonut = GravityIcon(0xf384);

  /// `Icon(GravityIcons.chartLine)`.
  static const GravityIcon chartLine = GravityIcon(0xf380);

  /// `Icon(GravityIcons.chartLineArrowUp)`.
  static const GravityIcon chartLineArrowUp = GravityIcon(0xf383);

  /// `Icon(GravityIcons.chartLineLabel)`.
  static const GravityIcon chartLineLabel = GravityIcon(0xf382);

  /// `Icon(GravityIcons.chartLinePoints)`.
  static const GravityIcon chartLinePoints = GravityIcon(0xf381);

  /// `Icon(GravityIcons.chartMixed)`.
  static const GravityIcon chartMixed = GravityIcon(0xf37f);

  /// `Icon(GravityIcons.chartPie)`.
  static const GravityIcon chartPie = GravityIcon(0xf37e);

  /// `Icon(GravityIcons.chartTreemap)`.
  static const GravityIcon chartTreemap = GravityIcon(0xf37d);

  /// `Icon(GravityIcons.check)`.
  static const GravityIcon check = GravityIcon(0xf379);

  /// `Icon(GravityIcons.checkDouble)`.
  static const GravityIcon checkDouble = GravityIcon(0xf37c);

  /// `Icon(GravityIcons.checkShape)`.
  static const GravityIcon checkShape = GravityIcon(0xf37a);

  /// `Icon(GravityIcons.checkShapeFill)`.
  static const GravityIcon checkShapeFill = GravityIcon(0xf37b);

  /// `Icon(GravityIcons.cherry)`.
  static const GravityIcon cherry = GravityIcon(0xf378);

  /// `Icon(GravityIcons.chevronDown)`.
  static const GravityIcon chevronDown = GravityIcon(0xf376);

  /// `Icon(GravityIcons.chevronDownWide)`.
  static const GravityIcon chevronDownWide = GravityIcon(0xf377);

  /// `Icon(GravityIcons.chevronLeft)`.
  static const GravityIcon chevronLeft = GravityIcon(0xf375);

  /// `Icon(GravityIcons.chevronRight)`.
  static const GravityIcon chevronRight = GravityIcon(0xf374);

  /// `Icon(GravityIcons.chevronUp)`.
  static const GravityIcon chevronUp = GravityIcon(0xf372);

  /// `Icon(GravityIcons.chevronUpWide)`.
  static const GravityIcon chevronUpWide = GravityIcon(0xf373);

  /// `Icon(GravityIcons.chevronsCollapseFromLines)`.
  static const GravityIcon chevronsCollapseFromLines = GravityIcon(0xf371);

  /// `Icon(GravityIcons.chevronsCollapseHorizontal)`.
  static const GravityIcon chevronsCollapseHorizontal = GravityIcon(0xf370);

  /// `Icon(GravityIcons.chevronsCollapseToLine)`.
  static const GravityIcon chevronsCollapseToLine = GravityIcon(0xf36f);

  /// `Icon(GravityIcons.chevronsCollapseUpRight)`.
  static const GravityIcon chevronsCollapseUpRight = GravityIcon(0xf36e);

  /// `Icon(GravityIcons.chevronsCollapseVertical)`.
  static const GravityIcon chevronsCollapseVertical = GravityIcon(0xf36d);

  /// `Icon(GravityIcons.chevronsDown)`.
  static const GravityIcon chevronsDown = GravityIcon(0xf36b);

  /// `Icon(GravityIcons.chevronsDownWide)`.
  static const GravityIcon chevronsDownWide = GravityIcon(0xf36c);

  /// `Icon(GravityIcons.chevronsExpandFromLine)`.
  static const GravityIcon chevronsExpandFromLine = GravityIcon(0xf36a);

  /// `Icon(GravityIcons.chevronsExpandHorizontal)`.
  static const GravityIcon chevronsExpandHorizontal = GravityIcon(0xf369);

  /// `Icon(GravityIcons.chevronsExpandToLines)`.
  static const GravityIcon chevronsExpandToLines = GravityIcon(0xf368);

  /// `Icon(GravityIcons.chevronsExpandUpRight)`.
  static const GravityIcon chevronsExpandUpRight = GravityIcon(0xf367);

  /// `Icon(GravityIcons.chevronsExpandVertical)`.
  static const GravityIcon chevronsExpandVertical = GravityIcon(0xf366);

  /// `Icon(GravityIcons.chevronsLeft)`.
  static const GravityIcon chevronsLeft = GravityIcon(0xf365);

  /// `Icon(GravityIcons.chevronsRight)`.
  static const GravityIcon chevronsRight = GravityIcon(0xf364);

  /// `Icon(GravityIcons.chevronsUp)`.
  static const GravityIcon chevronsUp = GravityIcon(0xf362);

  /// `Icon(GravityIcons.chevronsUpWide)`.
  static const GravityIcon chevronsUpWide = GravityIcon(0xf363);

  /// `Icon(GravityIcons.circle)`.
  static const GravityIcon circle = GravityIcon(0xf30e);

  /// `Icon(GravityIcons.circleArrowDown)`.
  static const GravityIcon circleArrowDown = GravityIcon(0xf360);

  /// `Icon(GravityIcons.circleArrowDownFill)`.
  static const GravityIcon circleArrowDownFill = GravityIcon(0xf361);

  /// `Icon(GravityIcons.circleArrowLeft)`.
  static const GravityIcon circleArrowLeft = GravityIcon(0xf35e);

  /// `Icon(GravityIcons.circleArrowLeftFill)`.
  static const GravityIcon circleArrowLeftFill = GravityIcon(0xf35f);

  /// `Icon(GravityIcons.circleArrowRight)`.
  static const GravityIcon circleArrowRight = GravityIcon(0xf35c);

  /// `Icon(GravityIcons.circleArrowRightFill)`.
  static const GravityIcon circleArrowRightFill = GravityIcon(0xf35d);

  /// `Icon(GravityIcons.circleArrowUp)`.
  static const GravityIcon circleArrowUp = GravityIcon(0xf35a);

  /// `Icon(GravityIcons.circleArrowUpFill)`.
  static const GravityIcon circleArrowUpFill = GravityIcon(0xf35b);

  /// `Icon(GravityIcons.circleCheck)`.
  static const GravityIcon circleCheck = GravityIcon(0xf358);

  /// `Icon(GravityIcons.circleCheckFill)`.
  static const GravityIcon circleCheckFill = GravityIcon(0xf359);

  /// `Icon(GravityIcons.circleChevronDown)`.
  static const GravityIcon circleChevronDown = GravityIcon(0xf356);

  /// `Icon(GravityIcons.circleChevronDownFill)`.
  static const GravityIcon circleChevronDownFill = GravityIcon(0xf357);

  /// `Icon(GravityIcons.circleChevronLeft)`.
  static const GravityIcon circleChevronLeft = GravityIcon(0xf354);

  /// `Icon(GravityIcons.circleChevronLeftFill)`.
  static const GravityIcon circleChevronLeftFill = GravityIcon(0xf355);

  /// `Icon(GravityIcons.circleChevronRight)`.
  static const GravityIcon circleChevronRight = GravityIcon(0xf352);

  /// `Icon(GravityIcons.circleChevronRightFill)`.
  static const GravityIcon circleChevronRightFill = GravityIcon(0xf353);

  /// `Icon(GravityIcons.circleChevronUp)`.
  static const GravityIcon circleChevronUp = GravityIcon(0xf350);

  /// `Icon(GravityIcons.circleChevronUpFill)`.
  static const GravityIcon circleChevronUpFill = GravityIcon(0xf351);

  /// `Icon(GravityIcons.circleChevronsDown)`.
  static const GravityIcon circleChevronsDown = GravityIcon(0xf34f);

  /// `Icon(GravityIcons.circleChevronsLeft)`.
  static const GravityIcon circleChevronsLeft = GravityIcon(0xf34e);

  /// `Icon(GravityIcons.circleChevronsRight)`.
  static const GravityIcon circleChevronsRight = GravityIcon(0xf34d);

  /// `Icon(GravityIcons.circleChevronsUp)`.
  static const GravityIcon circleChevronsUp = GravityIcon(0xf34c);

  /// `Icon(GravityIcons.circleDashed)`.
  static const GravityIcon circleDashed = GravityIcon(0xf34b);

  /// `Icon(GravityIcons.circleDollar)`.
  static const GravityIcon circleDollar = GravityIcon(0xf34a);

  /// `Icon(GravityIcons.circleExclamation)`.
  static const GravityIcon circleExclamation = GravityIcon(0xf348);

  /// `Icon(GravityIcons.circleExclamationFill)`.
  static const GravityIcon circleExclamationFill = GravityIcon(0xf349);

  /// `Icon(GravityIcons.circleFill)`.
  static const GravityIcon circleFill = GravityIcon(0xf347);

  /// `Icon(GravityIcons.circleInfo)`.
  static const GravityIcon circleInfo = GravityIcon(0xf345);

  /// `Icon(GravityIcons.circleInfoFill)`.
  static const GravityIcon circleInfoFill = GravityIcon(0xf346);

  /// `Icon(GravityIcons.circleLetterA)`.
  static const GravityIcon circleLetterA = GravityIcon(0xf344);

  /// `Icon(GravityIcons.circleLetterB)`.
  static const GravityIcon circleLetterB = GravityIcon(0xf343);

  /// `Icon(GravityIcons.circleLetterC)`.
  static const GravityIcon circleLetterC = GravityIcon(0xf342);

  /// `Icon(GravityIcons.circleLetterD)`.
  static const GravityIcon circleLetterD = GravityIcon(0xf341);

  /// `Icon(GravityIcons.circleLetterE)`.
  static const GravityIcon circleLetterE = GravityIcon(0xf340);

  /// `Icon(GravityIcons.circleLetterF)`.
  static const GravityIcon circleLetterF = GravityIcon(0xf33f);

  /// `Icon(GravityIcons.circleLetterG)`.
  static const GravityIcon circleLetterG = GravityIcon(0xf33e);

  /// `Icon(GravityIcons.circleLetterH)`.
  static const GravityIcon circleLetterH = GravityIcon(0xf33d);

  /// `Icon(GravityIcons.circleLetterI)`.
  static const GravityIcon circleLetterI = GravityIcon(0xf33c);

  /// `Icon(GravityIcons.circleLetterJ)`.
  static const GravityIcon circleLetterJ = GravityIcon(0xf33b);

  /// `Icon(GravityIcons.circleLetterK)`.
  static const GravityIcon circleLetterK = GravityIcon(0xf33a);

  /// `Icon(GravityIcons.circleLetterL)`.
  static const GravityIcon circleLetterL = GravityIcon(0xf339);

  /// `Icon(GravityIcons.circleLetterM)`.
  static const GravityIcon circleLetterM = GravityIcon(0xf338);

  /// `Icon(GravityIcons.circleLetterN)`.
  static const GravityIcon circleLetterN = GravityIcon(0xf337);

  /// `Icon(GravityIcons.circleLetterO)`.
  static const GravityIcon circleLetterO = GravityIcon(0xf336);

  /// `Icon(GravityIcons.circleLetterP)`.
  static const GravityIcon circleLetterP = GravityIcon(0xf335);

  /// `Icon(GravityIcons.circleLetterQ)`.
  static const GravityIcon circleLetterQ = GravityIcon(0xf334);

  /// `Icon(GravityIcons.circleLetterR)`.
  static const GravityIcon circleLetterR = GravityIcon(0xf333);

  /// `Icon(GravityIcons.circleLetterS)`.
  static const GravityIcon circleLetterS = GravityIcon(0xf332);

  /// `Icon(GravityIcons.circleLetterT)`.
  static const GravityIcon circleLetterT = GravityIcon(0xf331);

  /// `Icon(GravityIcons.circleLetterU)`.
  static const GravityIcon circleLetterU = GravityIcon(0xf330);

  /// `Icon(GravityIcons.circleLetterV)`.
  static const GravityIcon circleLetterV = GravityIcon(0xf32f);

  /// `Icon(GravityIcons.circleLetterW)`.
  static const GravityIcon circleLetterW = GravityIcon(0xf32e);

  /// `Icon(GravityIcons.circleLetterX)`.
  static const GravityIcon circleLetterX = GravityIcon(0xf32d);

  /// `Icon(GravityIcons.circleLetterY)`.
  static const GravityIcon circleLetterY = GravityIcon(0xf32c);

  /// `Icon(GravityIcons.circleLetterZ)`.
  static const GravityIcon circleLetterZ = GravityIcon(0xf32b);

  /// `Icon(GravityIcons.circleLink)`.
  static const GravityIcon circleLink = GravityIcon(0xf32a);

  /// `Icon(GravityIcons.circleMinus)`.
  static const GravityIcon circleMinus = GravityIcon(0xf328);

  /// `Icon(GravityIcons.circleMinusFill)`.
  static const GravityIcon circleMinusFill = GravityIcon(0xf329);

  /// `Icon(GravityIcons.circleNumber0)`.
  static const GravityIcon circleNumber0 = GravityIcon(0xf327);

  /// `Icon(GravityIcons.circleNumber1)`.
  static const GravityIcon circleNumber1 = GravityIcon(0xf326);

  /// `Icon(GravityIcons.circleNumber2)`.
  static const GravityIcon circleNumber2 = GravityIcon(0xf325);

  /// `Icon(GravityIcons.circleNumber3)`.
  static const GravityIcon circleNumber3 = GravityIcon(0xf324);

  /// `Icon(GravityIcons.circleNumber4)`.
  static const GravityIcon circleNumber4 = GravityIcon(0xf323);

  /// `Icon(GravityIcons.circleNumber5)`.
  static const GravityIcon circleNumber5 = GravityIcon(0xf322);

  /// `Icon(GravityIcons.circleNumber6)`.
  static const GravityIcon circleNumber6 = GravityIcon(0xf321);

  /// `Icon(GravityIcons.circleNumber7)`.
  static const GravityIcon circleNumber7 = GravityIcon(0xf320);

  /// `Icon(GravityIcons.circleNumber8)`.
  static const GravityIcon circleNumber8 = GravityIcon(0xf31f);

  /// `Icon(GravityIcons.circleNumber9)`.
  static const GravityIcon circleNumber9 = GravityIcon(0xf31e);

  /// `Icon(GravityIcons.circlePause)`.
  static const GravityIcon circlePause = GravityIcon(0xf31c);

  /// `Icon(GravityIcons.circlePauseFill)`.
  static const GravityIcon circlePauseFill = GravityIcon(0xf31d);

  /// `Icon(GravityIcons.circlePlay)`.
  static const GravityIcon circlePlay = GravityIcon(0xf31a);

  /// `Icon(GravityIcons.circlePlayFill)`.
  static const GravityIcon circlePlayFill = GravityIcon(0xf31b);

  /// `Icon(GravityIcons.circlePlus)`.
  static const GravityIcon circlePlus = GravityIcon(0xf318);

  /// `Icon(GravityIcons.circlePlusFill)`.
  static const GravityIcon circlePlusFill = GravityIcon(0xf319);

  /// `Icon(GravityIcons.circleQuestion)`.
  static const GravityIcon circleQuestion = GravityIcon(0xf315);

  /// `Icon(GravityIcons.circleQuestionDot)`.
  static const GravityIcon circleQuestionDot = GravityIcon(0xf317);

  /// `Icon(GravityIcons.circleQuestionFill)`.
  static const GravityIcon circleQuestionFill = GravityIcon(0xf316);

  /// `Icon(GravityIcons.circleRuble)`.
  static const GravityIcon circleRuble = GravityIcon(0xf314);

  /// `Icon(GravityIcons.circleStop)`.
  static const GravityIcon circleStop = GravityIcon(0xf312);

  /// `Icon(GravityIcons.circleStopFill)`.
  static const GravityIcon circleStopFill = GravityIcon(0xf313);

  /// `Icon(GravityIcons.circleTree)`.
  static const GravityIcon circleTree = GravityIcon(0xf311);

  /// `Icon(GravityIcons.circleXmark)`.
  static const GravityIcon circleXmark = GravityIcon(0xf30f);

  /// `Icon(GravityIcons.circleXmarkFill)`.
  static const GravityIcon circleXmarkFill = GravityIcon(0xf310);

  /// `Icon(GravityIcons.circles3Plus)`.
  static const GravityIcon circles3Plus = GravityIcon(0xf30d);

  /// `Icon(GravityIcons.circles4Diamond)`.
  static const GravityIcon circles4Diamond = GravityIcon(0xf30c);

  /// `Icon(GravityIcons.circles4Square)`.
  static const GravityIcon circles4Square = GravityIcon(0xf30b);

  /// `Icon(GravityIcons.circles5Random)`.
  static const GravityIcon circles5Random = GravityIcon(0xf30a);

  /// `Icon(GravityIcons.circlesConcentric)`.
  static const GravityIcon circlesConcentric = GravityIcon(0xf309);

  /// `Icon(GravityIcons.circlesIntersection)`.
  static const GravityIcon circlesIntersection = GravityIcon(0xf308);

  /// `Icon(GravityIcons.clock)`.
  static const GravityIcon clock = GravityIcon(0xf305);

  /// `Icon(GravityIcons.clockArrowRotateLeft)`.
  static const GravityIcon clockArrowRotateLeft = GravityIcon(0xf307);

  /// `Icon(GravityIcons.clockFill)`.
  static const GravityIcon clockFill = GravityIcon(0xf306);

  /// `Icon(GravityIcons.cloud)`.
  static const GravityIcon cloud = GravityIcon(0xf2ff);

  /// `Icon(GravityIcons.cloudArrowUpIn)`.
  static const GravityIcon cloudArrowUpIn = GravityIcon(0xf304);

  /// `Icon(GravityIcons.cloudCheck)`.
  static const GravityIcon cloudCheck = GravityIcon(0xf303);

  /// `Icon(GravityIcons.cloudGear)`.
  static const GravityIcon cloudGear = GravityIcon(0xf302);

  /// `Icon(GravityIcons.cloudNutHex)`.
  static const GravityIcon cloudNutHex = GravityIcon(0xf301);

  /// `Icon(GravityIcons.cloudSlash)`.
  static const GravityIcon cloudSlash = GravityIcon(0xf300);

  /// `Icon(GravityIcons.clouds)`.
  static const GravityIcon clouds = GravityIcon(0xf2fe);

  /// `Icon(GravityIcons.code)`.
  static const GravityIcon code = GravityIcon(0xf2f1);

  /// `Icon(GravityIcons.codeCommit)`.
  static const GravityIcon codeCommit = GravityIcon(0xf2fc);

  /// `Icon(GravityIcons.codeCommitHorizontal)`.
  static const GravityIcon codeCommitHorizontal = GravityIcon(0xf2fd);

  /// `Icon(GravityIcons.codeCommits)`.
  static const GravityIcon codeCommits = GravityIcon(0xf2fb);

  /// `Icon(GravityIcons.codeCompare)`.
  static const GravityIcon codeCompare = GravityIcon(0xf2fa);

  /// `Icon(GravityIcons.codeFork)`.
  static const GravityIcon codeFork = GravityIcon(0xf2f9);

  /// `Icon(GravityIcons.codeMerge)`.
  static const GravityIcon codeMerge = GravityIcon(0xf2f8);

  /// `Icon(GravityIcons.codePullRequest)`.
  static const GravityIcon codePullRequest = GravityIcon(0xf2f3);

  /// `Icon(GravityIcons.codePullRequestArrowLeft)`.
  static const GravityIcon codePullRequestArrowLeft = GravityIcon(0xf2f7);

  /// `Icon(GravityIcons.codePullRequestArrowRight)`.
  static const GravityIcon codePullRequestArrowRight = GravityIcon(0xf2f6);

  /// `Icon(GravityIcons.codePullRequestCheck)`.
  static const GravityIcon codePullRequestCheck = GravityIcon(0xf2f5);

  /// `Icon(GravityIcons.codePullRequestXmark)`.
  static const GravityIcon codePullRequestXmark = GravityIcon(0xf2f4);

  /// `Icon(GravityIcons.codeTrunk)`.
  static const GravityIcon codeTrunk = GravityIcon(0xf2f2);

  /// `Icon(GravityIcons.comment)`.
  static const GravityIcon comment = GravityIcon(0xf2ec);

  /// `Icon(GravityIcons.commentDot)`.
  static const GravityIcon commentDot = GravityIcon(0xf2f0);

  /// `Icon(GravityIcons.commentFill)`.
  static const GravityIcon commentFill = GravityIcon(0xf2ef);

  /// `Icon(GravityIcons.commentPlus)`.
  static const GravityIcon commentPlus = GravityIcon(0xf2ee);

  /// `Icon(GravityIcons.commentSlash)`.
  static const GravityIcon commentSlash = GravityIcon(0xf2ed);

  /// `Icon(GravityIcons.comments)`.
  static const GravityIcon comments = GravityIcon(0xf2eb);

  /// `Icon(GravityIcons.compass)`.
  static const GravityIcon compass = GravityIcon(0xf2ea);

  /// `Icon(GravityIcons.copy)`.
  static const GravityIcon copy = GravityIcon(0xf2e0);

  /// `Icon(GravityIcons.copyArrowRight)`.
  static const GravityIcon copyArrowRight = GravityIcon(0xf2e9);

  /// `Icon(GravityIcons.copyCheck)`.
  static const GravityIcon copyCheck = GravityIcon(0xf2e7);

  /// `Icon(GravityIcons.copyCheckXmark)`.
  static const GravityIcon copyCheckXmark = GravityIcon(0xf2e8);

  /// `Icon(GravityIcons.copyChevronRight)`.
  static const GravityIcon copyChevronRight = GravityIcon(0xf2e6);

  /// `Icon(GravityIcons.copyMinus)`.
  static const GravityIcon copyMinus = GravityIcon(0xf2e5);

  /// `Icon(GravityIcons.copyPicture)`.
  static const GravityIcon copyPicture = GravityIcon(0xf2e4);

  /// `Icon(GravityIcons.copyPlus)`.
  static const GravityIcon copyPlus = GravityIcon(0xf2e3);

  /// `Icon(GravityIcons.copyTransparent)`.
  static const GravityIcon copyTransparent = GravityIcon(0xf2e2);

  /// `Icon(GravityIcons.copyXmark)`.
  static const GravityIcon copyXmark = GravityIcon(0xf2e1);

  /// `Icon(GravityIcons.cpu)`.
  static const GravityIcon cpu = GravityIcon(0xf2df);

  /// `Icon(GravityIcons.cpus)`.
  static const GravityIcon cpus = GravityIcon(0xf2de);

  /// `Icon(GravityIcons.creditCard)`.
  static const GravityIcon creditCard = GravityIcon(0xf2dd);

  /// `Icon(GravityIcons.crop)`.
  static const GravityIcon crop = GravityIcon(0xf2dc);

  /// `Icon(GravityIcons.crownDiamond)`.
  static const GravityIcon crownDiamond = GravityIcon(0xf2db);

  /// `Icon(GravityIcons.cube)`.
  static const GravityIcon cube = GravityIcon(0xf2da);

  /// `Icon(GravityIcons.cubes3)`.
  static const GravityIcon cubes3 = GravityIcon(0xf2d8);

  /// `Icon(GravityIcons.cubes3Overlap)`.
  static const GravityIcon cubes3Overlap = GravityIcon(0xf2d9);

  /// `Icon(GravityIcons.cup)`.
  static const GravityIcon cup = GravityIcon(0xf2d7);

  /// `Icon(GravityIcons.curlyBrackets)`.
  static const GravityIcon curlyBrackets = GravityIcon(0xf2d4);

  /// `Icon(GravityIcons.curlyBracketsFunction)`.
  static const GravityIcon curlyBracketsFunction = GravityIcon(0xf2d6);

  /// `Icon(GravityIcons.curlyBracketsLock)`.
  static const GravityIcon curlyBracketsLock = GravityIcon(0xf2d5);

  /// `Icon(GravityIcons.database)`.
  static const GravityIcon database = GravityIcon(0xf2d0);

  /// `Icon(GravityIcons.databaseArrowRight)`.
  static const GravityIcon databaseArrowRight = GravityIcon(0xf2d3);

  /// `Icon(GravityIcons.databaseFill)`.
  static const GravityIcon databaseFill = GravityIcon(0xf2d2);

  /// `Icon(GravityIcons.databaseMagnifier)`.
  static const GravityIcon databaseMagnifier = GravityIcon(0xf2d1);

  /// `Icon(GravityIcons.databases)`.
  static const GravityIcon databases = GravityIcon(0xf2ce);

  /// `Icon(GravityIcons.databasesFill)`.
  static const GravityIcon databasesFill = GravityIcon(0xf2cf);

  /// `Icon(GravityIcons.delete)`.
  static const GravityIcon delete = GravityIcon(0xf2cd);

  /// `Icon(GravityIcons.diamond)`.
  static const GravityIcon diamond = GravityIcon(0xf2c9);

  /// `Icon(GravityIcons.diamondExclamation)`.
  static const GravityIcon diamondExclamation = GravityIcon(0xf2cb);

  /// `Icon(GravityIcons.diamondExclamationFill)`.
  static const GravityIcon diamondExclamationFill = GravityIcon(0xf2cc);

  /// `Icon(GravityIcons.diamondFill)`.
  static const GravityIcon diamondFill = GravityIcon(0xf2ca);

  /// `Icon(GravityIcons.dice1)`.
  static const GravityIcon dice1 = GravityIcon(0xf2c8);

  /// `Icon(GravityIcons.dice2)`.
  static const GravityIcon dice2 = GravityIcon(0xf2c7);

  /// `Icon(GravityIcons.dice3)`.
  static const GravityIcon dice3 = GravityIcon(0xf2c6);

  /// `Icon(GravityIcons.dice4)`.
  static const GravityIcon dice4 = GravityIcon(0xf2c5);

  /// `Icon(GravityIcons.dice5)`.
  static const GravityIcon dice5 = GravityIcon(0xf2c4);

  /// `Icon(GravityIcons.dice6)`.
  static const GravityIcon dice6 = GravityIcon(0xf2c3);

  /// `Icon(GravityIcons.display)`.
  static const GravityIcon display = GravityIcon(0xf2c1);

  /// `Icon(GravityIcons.displayPulse)`.
  static const GravityIcon displayPulse = GravityIcon(0xf2c2);

  /// `Icon(GravityIcons.dots9)`.
  static const GravityIcon dots9 = GravityIcon(0xf2c0);

  /// `Icon(GravityIcons.droplet)`.
  static const GravityIcon droplet = GravityIcon(0xf2bf);

  /// `Icon(GravityIcons.ear)`.
  static const GravityIcon ear = GravityIcon(0xf2be);

  /// `Icon(GravityIcons.ellipsis)`.
  static const GravityIcon ellipsis = GravityIcon(0xf2bc);

  /// `Icon(GravityIcons.ellipsisVertical)`.
  static const GravityIcon ellipsisVertical = GravityIcon(0xf2bd);

  /// `Icon(GravityIcons.envelope)`.
  static const GravityIcon envelope = GravityIcon(0xf2b9);

  /// `Icon(GravityIcons.envelopeOpen)`.
  static const GravityIcon envelopeOpen = GravityIcon(0xf2ba);

  /// `Icon(GravityIcons.envelopeOpenXmark)`.
  static const GravityIcon envelopeOpenXmark = GravityIcon(0xf2bb);

  /// `Icon(GravityIcons.equal)`.
  static const GravityIcon equal = GravityIcon(0xf2b8);

  /// `Icon(GravityIcons.eraser)`.
  static const GravityIcon eraser = GravityIcon(0xf2b7);

  /// `Icon(GravityIcons.exclamationShape)`.
  static const GravityIcon exclamationShape = GravityIcon(0xf2b5);

  /// `Icon(GravityIcons.exclamationShapeFill)`.
  static const GravityIcon exclamationShapeFill = GravityIcon(0xf2b6);

  /// `Icon(GravityIcons.eye)`.
  static const GravityIcon eye = GravityIcon(0xf2b1);

  /// `Icon(GravityIcons.eyeClosed)`.
  static const GravityIcon eyeClosed = GravityIcon(0xf2b4);

  /// `Icon(GravityIcons.eyeDashed)`.
  static const GravityIcon eyeDashed = GravityIcon(0xf2b3);

  /// `Icon(GravityIcons.eyeSlash)`.
  static const GravityIcon eyeSlash = GravityIcon(0xf2b2);

  /// `Icon(GravityIcons.eyesLookLeft)`.
  static const GravityIcon eyesLookLeft = GravityIcon(0xf2b0);

  /// `Icon(GravityIcons.eyesLookRight)`.
  static const GravityIcon eyesLookRight = GravityIcon(0xf2af);

  /// `Icon(GravityIcons.faceAlien)`.
  static const GravityIcon faceAlien = GravityIcon(0xf2ae);

  /// `Icon(GravityIcons.faceAngry)`.
  static const GravityIcon faceAngry = GravityIcon(0xf2ad);

  /// `Icon(GravityIcons.faceFun)`.
  static const GravityIcon faceFun = GravityIcon(0xf2ac);

  /// `Icon(GravityIcons.faceNeutral)`.
  static const GravityIcon faceNeutral = GravityIcon(0xf2aa);

  /// `Icon(GravityIcons.faceNeutralDashed)`.
  static const GravityIcon faceNeutralDashed = GravityIcon(0xf2ab);

  /// `Icon(GravityIcons.faceRobot)`.
  static const GravityIcon faceRobot = GravityIcon(0xf2a8);

  /// `Icon(GravityIcons.faceRobotSmile)`.
  static const GravityIcon faceRobotSmile = GravityIcon(0xf2a9);

  /// `Icon(GravityIcons.faceSad)`.
  static const GravityIcon faceSad = GravityIcon(0xf2a7);

  /// `Icon(GravityIcons.faceSmile)`.
  static const GravityIcon faceSmile = GravityIcon(0xf2a6);

  /// `Icon(GravityIcons.faceSurprise)`.
  static const GravityIcon faceSurprise = GravityIcon(0xf2a5);

  /// `Icon(GravityIcons.factory)`.
  static const GravityIcon factory = GravityIcon(0xf2a4);

  /// `Icon(GravityIcons.file)`.
  static const GravityIcon file = GravityIcon(0xf28f);

  /// `Icon(GravityIcons.fileArrowDown)`.
  static const GravityIcon fileArrowDown = GravityIcon(0xf2a3);

  /// `Icon(GravityIcons.fileArrowLeft)`.
  static const GravityIcon fileArrowLeft = GravityIcon(0xf2a2);

  /// `Icon(GravityIcons.fileArrowRight)`.
  static const GravityIcon fileArrowRight = GravityIcon(0xf2a0);

  /// `Icon(GravityIcons.fileArrowRightOut)`.
  static const GravityIcon fileArrowRightOut = GravityIcon(0xf2a1);

  /// `Icon(GravityIcons.fileArrowUp)`.
  static const GravityIcon fileArrowUp = GravityIcon(0xf29f);

  /// `Icon(GravityIcons.fileCheck)`.
  static const GravityIcon fileCheck = GravityIcon(0xf29e);

  /// `Icon(GravityIcons.fileCode)`.
  static const GravityIcon fileCode = GravityIcon(0xf29d);

  /// `Icon(GravityIcons.fileDollar)`.
  static const GravityIcon fileDollar = GravityIcon(0xf29c);

  /// `Icon(GravityIcons.fileExclamation)`.
  static const GravityIcon fileExclamation = GravityIcon(0xf29b);

  /// `Icon(GravityIcons.fileLetterP)`.
  static const GravityIcon fileLetterP = GravityIcon(0xf29a);

  /// `Icon(GravityIcons.fileLetterW)`.
  static const GravityIcon fileLetterW = GravityIcon(0xf299);

  /// `Icon(GravityIcons.fileLetterX)`.
  static const GravityIcon fileLetterX = GravityIcon(0xf298);

  /// `Icon(GravityIcons.fileMagnifier)`.
  static const GravityIcon fileMagnifier = GravityIcon(0xf297);

  /// `Icon(GravityIcons.fileMinus)`.
  static const GravityIcon fileMinus = GravityIcon(0xf296);

  /// `Icon(GravityIcons.filePlus)`.
  static const GravityIcon filePlus = GravityIcon(0xf295);

  /// `Icon(GravityIcons.fileQuestion)`.
  static const GravityIcon fileQuestion = GravityIcon(0xf294);

  /// `Icon(GravityIcons.fileRuble)`.
  static const GravityIcon fileRuble = GravityIcon(0xf293);

  /// `Icon(GravityIcons.fileText)`.
  static const GravityIcon fileText = GravityIcon(0xf292);

  /// `Icon(GravityIcons.fileXmark)`.
  static const GravityIcon fileXmark = GravityIcon(0xf291);

  /// `Icon(GravityIcons.fileZipper)`.
  static const GravityIcon fileZipper = GravityIcon(0xf290);

  /// `Icon(GravityIcons.files)`.
  static const GravityIcon files = GravityIcon(0xf28e);

  /// `Icon(GravityIcons.filmstrip)`.
  static const GravityIcon filmstrip = GravityIcon(0xf28d);

  /// `Icon(GravityIcons.fingerprint)`.
  static const GravityIcon fingerprint = GravityIcon(0xf28c);

  /// `Icon(GravityIcons.firewall)`.
  static const GravityIcon firewall = GravityIcon(0xf28b);

  /// `Icon(GravityIcons.flag)`.
  static const GravityIcon flag = GravityIcon(0xf28a);

  /// `Icon(GravityIcons.flame)`.
  static const GravityIcon flame = GravityIcon(0xf289);

  /// `Icon(GravityIcons.flask)`.
  static const GravityIcon flask = GravityIcon(0xf288);

  /// `Icon(GravityIcons.floppyDisk)`.
  static const GravityIcon floppyDisk = GravityIcon(0xf287);

  /// `Icon(GravityIcons.folder)`.
  static const GravityIcon folder = GravityIcon(0xf274);

  /// `Icon(GravityIcons.folderArrowDown)`.
  static const GravityIcon folderArrowDown = GravityIcon(0xf286);

  /// `Icon(GravityIcons.folderArrowLeft)`.
  static const GravityIcon folderArrowLeft = GravityIcon(0xf285);

  /// `Icon(GravityIcons.folderArrowRight)`.
  static const GravityIcon folderArrowRight = GravityIcon(0xf284);

  /// `Icon(GravityIcons.folderArrowUp)`.
  static const GravityIcon folderArrowUp = GravityIcon(0xf282);

  /// `Icon(GravityIcons.folderArrowUpIn)`.
  static const GravityIcon folderArrowUpIn = GravityIcon(0xf283);

  /// `Icon(GravityIcons.folderCheck)`.
  static const GravityIcon folderCheck = GravityIcon(0xf281);

  /// `Icon(GravityIcons.folderCode)`.
  static const GravityIcon folderCode = GravityIcon(0xf280);

  /// `Icon(GravityIcons.folderExclamation)`.
  static const GravityIcon folderExclamation = GravityIcon(0xf27f);

  /// `Icon(GravityIcons.folderFill)`.
  static const GravityIcon folderFill = GravityIcon(0xf27e);

  /// `Icon(GravityIcons.folderFlows)`.
  static const GravityIcon folderFlows = GravityIcon(0xf27d);

  /// `Icon(GravityIcons.folderHouse)`.
  static const GravityIcon folderHouse = GravityIcon(0xf27c);

  /// `Icon(GravityIcons.folderKeyhole)`.
  static const GravityIcon folderKeyhole = GravityIcon(0xf27b);

  /// `Icon(GravityIcons.folderLock)`.
  static const GravityIcon folderLock = GravityIcon(0xf27a);

  /// `Icon(GravityIcons.folderMagnifier)`.
  static const GravityIcon folderMagnifier = GravityIcon(0xf279);

  /// `Icon(GravityIcons.folderOpen)`.
  static const GravityIcon folderOpen = GravityIcon(0xf277);

  /// `Icon(GravityIcons.folderOpenFill)`.
  static const GravityIcon folderOpenFill = GravityIcon(0xf278);

  /// `Icon(GravityIcons.folderPlus)`.
  static const GravityIcon folderPlus = GravityIcon(0xf276);

  /// `Icon(GravityIcons.folderTree)`.
  static const GravityIcon folderTree = GravityIcon(0xf275);

  /// `Icon(GravityIcons.folders)`.
  static const GravityIcon folders = GravityIcon(0xf273);

  /// `Icon(GravityIcons.font)`.
  static const GravityIcon font = GravityIcon(0xf270);

  /// `Icon(GravityIcons.fontCase)`.
  static const GravityIcon fontCase = GravityIcon(0xf272);

  /// `Icon(GravityIcons.fontCursor)`.
  static const GravityIcon fontCursor = GravityIcon(0xf271);

  /// `Icon(GravityIcons.forwardStep)`.
  static const GravityIcon forwardStep = GravityIcon(0xf26e);

  /// `Icon(GravityIcons.forwardStepFill)`.
  static const GravityIcon forwardStepFill = GravityIcon(0xf26f);

  /// `Icon(GravityIcons.frame)`.
  static const GravityIcon frame = GravityIcon(0xf26d);

  /// `Icon(GravityIcons.frames)`.
  static const GravityIcon frames = GravityIcon(0xf26c);

  /// `Icon(GravityIcons.function)`.
  static const GravityIcon function = GravityIcon(0xf26b);

  /// `Icon(GravityIcons.funnel)`.
  static const GravityIcon funnel = GravityIcon(0xf269);

  /// `Icon(GravityIcons.funnelXmark)`.
  static const GravityIcon funnelXmark = GravityIcon(0xf26a);

  /// `Icon(GravityIcons.gear)`.
  static const GravityIcon gear = GravityIcon(0xf265);

  /// `Icon(GravityIcons.gearBranches)`.
  static const GravityIcon gearBranches = GravityIcon(0xf268);

  /// `Icon(GravityIcons.gearDot)`.
  static const GravityIcon gearDot = GravityIcon(0xf267);

  /// `Icon(GravityIcons.gearPlay)`.
  static const GravityIcon gearPlay = GravityIcon(0xf266);

  /// `Icon(GravityIcons.gem)`.
  static const GravityIcon gem = GravityIcon(0xf264);

  /// `Icon(GravityIcons.geo)`.
  static const GravityIcon geo = GravityIcon(0xf25f);

  /// `Icon(GravityIcons.geoDots)`.
  static const GravityIcon geoDots = GravityIcon(0xf263);

  /// `Icon(GravityIcons.geoFill)`.
  static const GravityIcon geoFill = GravityIcon(0xf262);

  /// `Icon(GravityIcons.geoPin)`.
  static const GravityIcon geoPin = GravityIcon(0xf261);

  /// `Icon(GravityIcons.geoPolygons)`.
  static const GravityIcon geoPolygons = GravityIcon(0xf260);

  /// `Icon(GravityIcons.ghost)`.
  static const GravityIcon ghost = GravityIcon(0xf25e);

  /// `Icon(GravityIcons.gift)`.
  static const GravityIcon gift = GravityIcon(0xf25d);

  /// `Icon(GravityIcons.globe)`.
  static const GravityIcon globe = GravityIcon(0xf25c);

  /// `Icon(GravityIcons.gpu)`.
  static const GravityIcon gpu = GravityIcon(0xf25b);

  /// `Icon(GravityIcons.graduationCap)`.
  static const GravityIcon graduationCap = GravityIcon(0xf25a);

  /// `Icon(GravityIcons.graphNode)`.
  static const GravityIcon graphNode = GravityIcon(0xf259);

  /// `Icon(GravityIcons.grip)`.
  static const GravityIcon grip = GravityIcon(0xf257);

  /// `Icon(GravityIcons.gripHorizontal)`.
  static const GravityIcon gripHorizontal = GravityIcon(0xf258);

  /// `Icon(GravityIcons.hammer)`.
  static const GravityIcon hammer = GravityIcon(0xf256);

  /// `Icon(GravityIcons.hand)`.
  static const GravityIcon hand = GravityIcon(0xf24f);

  /// `Icon(GravityIcons.handOk)`.
  static const GravityIcon handOk = GravityIcon(0xf255);

  /// `Icon(GravityIcons.handPointDown)`.
  static const GravityIcon handPointDown = GravityIcon(0xf254);

  /// `Icon(GravityIcons.handPointLeft)`.
  static const GravityIcon handPointLeft = GravityIcon(0xf253);

  /// `Icon(GravityIcons.handPointRight)`.
  static const GravityIcon handPointRight = GravityIcon(0xf252);

  /// `Icon(GravityIcons.handPointUp)`.
  static const GravityIcon handPointUp = GravityIcon(0xf251);

  /// `Icon(GravityIcons.handStop)`.
  static const GravityIcon handStop = GravityIcon(0xf250);

  /// `Icon(GravityIcons.handset)`.
  static const GravityIcon handset = GravityIcon(0xf24c);

  /// `Icon(GravityIcons.handsetArrowIn)`.
  static const GravityIcon handsetArrowIn = GravityIcon(0xf24e);

  /// `Icon(GravityIcons.handsetArrowOut)`.
  static const GravityIcon handsetArrowOut = GravityIcon(0xf24d);

  /// `Icon(GravityIcons.hardDrive)`.
  static const GravityIcon hardDrive = GravityIcon(0xf24b);

  /// `Icon(GravityIcons.hashtag)`.
  static const GravityIcon hashtag = GravityIcon(0xf24a);

  /// `Icon(GravityIcons.heading)`.
  static const GravityIcon heading = GravityIcon(0xf243);

  /// `Icon(GravityIcons.heading1)`.
  static const GravityIcon heading1 = GravityIcon(0xf249);

  /// `Icon(GravityIcons.heading2)`.
  static const GravityIcon heading2 = GravityIcon(0xf248);

  /// `Icon(GravityIcons.heading3)`.
  static const GravityIcon heading3 = GravityIcon(0xf247);

  /// `Icon(GravityIcons.heading4)`.
  static const GravityIcon heading4 = GravityIcon(0xf246);

  /// `Icon(GravityIcons.heading5)`.
  static const GravityIcon heading5 = GravityIcon(0xf245);

  /// `Icon(GravityIcons.heading6)`.
  static const GravityIcon heading6 = GravityIcon(0xf244);

  /// `Icon(GravityIcons.headphones)`.
  static const GravityIcon headphones = GravityIcon(0xf242);

  /// `Icon(GravityIcons.heart)`.
  static const GravityIcon heart = GravityIcon(0xf23e);

  /// `Icon(GravityIcons.heartCrack)`.
  static const GravityIcon heartCrack = GravityIcon(0xf241);

  /// `Icon(GravityIcons.heartFill)`.
  static const GravityIcon heartFill = GravityIcon(0xf240);

  /// `Icon(GravityIcons.heartPulse)`.
  static const GravityIcon heartPulse = GravityIcon(0xf23f);

  /// `Icon(GravityIcons.hierarchy)`.
  static const GravityIcon hierarchy = GravityIcon(0xf23d);

  /// `Icon(GravityIcons.house)`.
  static const GravityIcon house = GravityIcon(0xf23b);

  /// `Icon(GravityIcons.houseFill)`.
  static const GravityIcon houseFill = GravityIcon(0xf23c);

  /// `Icon(GravityIcons.italic)`.
  static const GravityIcon italic = GravityIcon(0xf23a);

  /// `Icon(GravityIcons.key)`.
  static const GravityIcon key = GravityIcon(0xf239);

  /// `Icon(GravityIcons.keyboard)`.
  static const GravityIcon keyboard = GravityIcon(0xf238);

  /// `Icon(GravityIcons.layers)`.
  static const GravityIcon layers = GravityIcon(0xf235);

  /// `Icon(GravityIcons.layers3Diagonal)`.
  static const GravityIcon layers3Diagonal = GravityIcon(0xf237);

  /// `Icon(GravityIcons.layersVertical)`.
  static const GravityIcon layersVertical = GravityIcon(0xf236);

  /// `Icon(GravityIcons.layoutCells)`.
  static const GravityIcon layoutCells = GravityIcon(0xf233);

  /// `Icon(GravityIcons.layoutCellsLarge)`.
  static const GravityIcon layoutCellsLarge = GravityIcon(0xf234);

  /// `Icon(GravityIcons.layoutColumns)`.
  static const GravityIcon layoutColumns = GravityIcon(0xf231);

  /// `Icon(GravityIcons.layoutColumns3)`.
  static const GravityIcon layoutColumns3 = GravityIcon(0xf232);

  /// `Icon(GravityIcons.layoutFooter)`.
  static const GravityIcon layoutFooter = GravityIcon(0xf230);

  /// `Icon(GravityIcons.layoutHeader)`.
  static const GravityIcon layoutHeader = GravityIcon(0xf227);

  /// `Icon(GravityIcons.layoutHeaderCells)`.
  static const GravityIcon layoutHeaderCells = GravityIcon(0xf22b);

  /// `Icon(GravityIcons.layoutHeaderCellsLarge)`.
  static const GravityIcon layoutHeaderCellsLarge = GravityIcon(0xf22c);

  /// `Icon(GravityIcons.layoutHeaderCellsLargeFill)`.
  static const GravityIcon layoutHeaderCellsLargeFill = GravityIcon(0xf22f);

  /// `Icon(GravityIcons.layoutHeaderCellsLargeLetterD)`.
  static const GravityIcon layoutHeaderCellsLargeLetterD = GravityIcon(0xf22e);

  /// `Icon(GravityIcons.layoutHeaderCellsLargeThunderbolt)`.
  static const GravityIcon layoutHeaderCellsLargeThunderbolt = GravityIcon(
    0xf22d,
  );

  /// `Icon(GravityIcons.layoutHeaderColumns)`.
  static const GravityIcon layoutHeaderColumns = GravityIcon(0xf22a);

  /// `Icon(GravityIcons.layoutHeaderCursor)`.
  static const GravityIcon layoutHeaderCursor = GravityIcon(0xf229);

  /// `Icon(GravityIcons.layoutHeaderSideContent)`.
  static const GravityIcon layoutHeaderSideContent = GravityIcon(0xf228);

  /// `Icon(GravityIcons.layoutList)`.
  static const GravityIcon layoutList = GravityIcon(0xf226);

  /// `Icon(GravityIcons.layoutRows)`.
  static const GravityIcon layoutRows = GravityIcon(0xf224);

  /// `Icon(GravityIcons.layoutRows3)`.
  static const GravityIcon layoutRows3 = GravityIcon(0xf225);

  /// `Icon(GravityIcons.layoutSideContent)`.
  static const GravityIcon layoutSideContent = GravityIcon(0xf221);

  /// `Icon(GravityIcons.layoutSideContentLeft)`.
  static const GravityIcon layoutSideContentLeft = GravityIcon(0xf223);

  /// `Icon(GravityIcons.layoutSideContentRight)`.
  static const GravityIcon layoutSideContentRight = GravityIcon(0xf222);

  /// `Icon(GravityIcons.layoutSplitColumns)`.
  static const GravityIcon layoutSplitColumns = GravityIcon(0xf21f);

  /// `Icon(GravityIcons.layoutSplitColumns3)`.
  static const GravityIcon layoutSplitColumns3 = GravityIcon(0xf220);

  /// `Icon(GravityIcons.layoutSplitRows)`.
  static const GravityIcon layoutSplitRows = GravityIcon(0xf21e);

  /// `Icon(GravityIcons.layoutSplitSideContentLeft)`.
  static const GravityIcon layoutSplitSideContentLeft = GravityIcon(0xf21d);

  /// `Icon(GravityIcons.layoutSplitSideContentRight)`.
  static const GravityIcon layoutSplitSideContentRight = GravityIcon(0xf21c);

  /// `Icon(GravityIcons.layoutTabs)`.
  static const GravityIcon layoutTabs = GravityIcon(0xf21b);

  /// `Icon(GravityIcons.letterAUnderline)`.
  static const GravityIcon letterAUnderline = GravityIcon(0xf21a);

  /// `Icon(GravityIcons.letterGroup)`.
  static const GravityIcon letterGroup = GravityIcon(0xf219);

  /// `Icon(GravityIcons.letterM)`.
  static const GravityIcon letterM = GravityIcon(0xf218);

  /// `Icon(GravityIcons.lifeRing)`.
  static const GravityIcon lifeRing = GravityIcon(0xf217);

  /// `Icon(GravityIcons.link)`.
  static const GravityIcon link = GravityIcon(0xf215);

  /// `Icon(GravityIcons.linkSlash)`.
  static const GravityIcon linkSlash = GravityIcon(0xf216);

  /// `Icon(GravityIcons.listCheck)`.
  static const GravityIcon listCheck = GravityIcon(0xf213);

  /// `Icon(GravityIcons.listCheckLock)`.
  static const GravityIcon listCheckLock = GravityIcon(0xf214);

  /// `Icon(GravityIcons.listOl)`.
  static const GravityIcon listOl = GravityIcon(0xf212);

  /// `Icon(GravityIcons.listTimeline)`.
  static const GravityIcon listTimeline = GravityIcon(0xf211);

  /// `Icon(GravityIcons.listUl)`.
  static const GravityIcon listUl = GravityIcon(0xf210);

  /// `Icon(GravityIcons.locationArrow)`.
  static const GravityIcon locationArrow = GravityIcon(0xf20e);

  /// `Icon(GravityIcons.locationArrowFill)`.
  static const GravityIcon locationArrowFill = GravityIcon(0xf20f);

  /// `Icon(GravityIcons.lock)`.
  static const GravityIcon lock = GravityIcon(0xf20a);

  /// `Icon(GravityIcons.lockFill)`.
  static const GravityIcon lockFill = GravityIcon(0xf20d);

  /// `Icon(GravityIcons.lockOpen)`.
  static const GravityIcon lockOpen = GravityIcon(0xf20b);

  /// `Icon(GravityIcons.lockOpenFill)`.
  static const GravityIcon lockOpenFill = GravityIcon(0xf20c);

  /// `Icon(GravityIcons.logoAcrobat)`.
  static const GravityIcon logoAcrobat = GravityIcon(0xf209);

  /// `Icon(GravityIcons.logoAndroid)`.
  static const GravityIcon logoAndroid = GravityIcon(0xf208);

  /// `Icon(GravityIcons.logoDebian)`.
  static const GravityIcon logoDebian = GravityIcon(0xf207);

  /// `Icon(GravityIcons.logoDocker)`.
  static const GravityIcon logoDocker = GravityIcon(0xf206);

  /// `Icon(GravityIcons.logoDrawIo)`.
  static const GravityIcon logoDrawIo = GravityIcon(0xf205);

  /// `Icon(GravityIcons.logoFacebook)`.
  static const GravityIcon logoFacebook = GravityIcon(0xf204);

  /// `Icon(GravityIcons.logoFigma)`.
  static const GravityIcon logoFigma = GravityIcon(0xf203);

  /// `Icon(GravityIcons.logoGithub)`.
  static const GravityIcon logoGithub = GravityIcon(0xf202);

  /// `Icon(GravityIcons.logoGitlab)`.
  static const GravityIcon logoGitlab = GravityIcon(0xf201);

  /// `Icon(GravityIcons.logoLinkedin)`.
  static const GravityIcon logoLinkedin = GravityIcon(0xf200);

  /// `Icon(GravityIcons.logoLinux)`.
  static const GravityIcon logoLinux = GravityIcon(0xf1ff);

  /// `Icon(GravityIcons.logoMacos)`.
  static const GravityIcon logoMacos = GravityIcon(0xf1fe);

  /// `Icon(GravityIcons.logoMarkdown)`.
  static const GravityIcon logoMarkdown = GravityIcon(0xf1fd);

  /// `Icon(GravityIcons.logoMcp)`.
  static const GravityIcon logoMcp = GravityIcon(0xf1fc);

  /// `Icon(GravityIcons.logoMermaid)`.
  static const GravityIcon logoMermaid = GravityIcon(0xf1fb);

  /// `Icon(GravityIcons.logoMicrosoftOffice)`.
  static const GravityIcon logoMicrosoftOffice = GravityIcon(0xf1fa);

  /// `Icon(GravityIcons.logoNodejs)`.
  static const GravityIcon logoNodejs = GravityIcon(0xf1f9);

  /// `Icon(GravityIcons.logoNotion)`.
  static const GravityIcon logoNotion = GravityIcon(0xf1f8);

  /// `Icon(GravityIcons.logoOsi)`.
  static const GravityIcon logoOsi = GravityIcon(0xf1f7);

  /// `Icon(GravityIcons.logoPython)`.
  static const GravityIcon logoPython = GravityIcon(0xf1f6);

  /// `Icon(GravityIcons.logoSlack)`.
  static const GravityIcon logoSlack = GravityIcon(0xf1f5);

  /// `Icon(GravityIcons.logoStackOverflow)`.
  static const GravityIcon logoStackOverflow = GravityIcon(0xf1f4);

  /// `Icon(GravityIcons.logoTelegram)`.
  static const GravityIcon logoTelegram = GravityIcon(0xf1f3);

  /// `Icon(GravityIcons.logoUbuntu)`.
  static const GravityIcon logoUbuntu = GravityIcon(0xf1f2);

  /// `Icon(GravityIcons.logoWindows)`.
  static const GravityIcon logoWindows = GravityIcon(0xf1f1);

  /// `Icon(GravityIcons.logoYandex)`.
  static const GravityIcon logoYandex = GravityIcon(0xf1ed);

  /// `Icon(GravityIcons.logoYandexCloud)`.
  static const GravityIcon logoYandexCloud = GravityIcon(0xf1f0);

  /// `Icon(GravityIcons.logoYandexMessenger)`.
  static const GravityIcon logoYandexMessenger = GravityIcon(0xf1ef);

  /// `Icon(GravityIcons.logoYandexTracker)`.
  static const GravityIcon logoYandexTracker = GravityIcon(0xf1ee);

  /// `Icon(GravityIcons.magicWand)`.
  static const GravityIcon magicWand = GravityIcon(0xf1ec);

  /// `Icon(GravityIcons.magnet)`.
  static const GravityIcon magnet = GravityIcon(0xf1eb);

  /// `Icon(GravityIcons.magnifier)`.
  static const GravityIcon magnifier = GravityIcon(0xf1e8);

  /// `Icon(GravityIcons.magnifierMinus)`.
  static const GravityIcon magnifierMinus = GravityIcon(0xf1ea);

  /// `Icon(GravityIcons.magnifierPlus)`.
  static const GravityIcon magnifierPlus = GravityIcon(0xf1e9);

  /// `Icon(GravityIcons.mapPin)`.
  static const GravityIcon mapPin = GravityIcon(0xf1e5);

  /// `Icon(GravityIcons.mapPinMinus)`.
  static const GravityIcon mapPinMinus = GravityIcon(0xf1e7);

  /// `Icon(GravityIcons.mapPinPlus)`.
  static const GravityIcon mapPinPlus = GravityIcon(0xf1e6);

  /// `Icon(GravityIcons.mathIntersectionShape)`.
  static const GravityIcon mathIntersectionShape = GravityIcon(0xf1e4);

  /// `Icon(GravityIcons.mathOperations)`.
  static const GravityIcon mathOperations = GravityIcon(0xf1e3);

  /// `Icon(GravityIcons.mathUnionShape)`.
  static const GravityIcon mathUnionShape = GravityIcon(0xf1e2);

  /// `Icon(GravityIcons.medal)`.
  static const GravityIcon medal = GravityIcon(0xf1e1);

  /// `Icon(GravityIcons.megaphone)`.
  static const GravityIcon megaphone = GravityIcon(0xf1e0);

  /// `Icon(GravityIcons.microphone)`.
  static const GravityIcon microphone = GravityIcon(0xf1de);

  /// `Icon(GravityIcons.microphoneSlash)`.
  static const GravityIcon microphoneSlash = GravityIcon(0xf1df);

  /// `Icon(GravityIcons.microscope)`.
  static const GravityIcon microscope = GravityIcon(0xf1dd);

  /// `Icon(GravityIcons.minus)`.
  static const GravityIcon minus = GravityIcon(0xf1da);

  /// `Icon(GravityIcons.minusShape)`.
  static const GravityIcon minusShape = GravityIcon(0xf1db);

  /// `Icon(GravityIcons.minusShapeFill)`.
  static const GravityIcon minusShapeFill = GravityIcon(0xf1dc);

  /// `Icon(GravityIcons.molecule)`.
  static const GravityIcon molecule = GravityIcon(0xf1d9);

  /// `Icon(GravityIcons.moon)`.
  static const GravityIcon moon = GravityIcon(0xf1d8);

  /// `Icon(GravityIcons.mug)`.
  static const GravityIcon mug = GravityIcon(0xf1d7);

  /// `Icon(GravityIcons.musicNote)`.
  static const GravityIcon musicNote = GravityIcon(0xf1d6);

  /// `Icon(GravityIcons.nodesDown)`.
  static const GravityIcon nodesDown = GravityIcon(0xf1d5);

  /// `Icon(GravityIcons.nodesLeft)`.
  static const GravityIcon nodesLeft = GravityIcon(0xf1d4);

  /// `Icon(GravityIcons.nodesRight)`.
  static const GravityIcon nodesRight = GravityIcon(0xf1d3);

  /// `Icon(GravityIcons.nodesUp)`.
  static const GravityIcon nodesUp = GravityIcon(0xf1d2);

  /// `Icon(GravityIcons.nutHex)`.
  static const GravityIcon nutHex = GravityIcon(0xf1d1);

  /// `Icon(GravityIcons.objectAlignBottom)`.
  static const GravityIcon objectAlignBottom = GravityIcon(0xf1d0);

  /// `Icon(GravityIcons.objectAlignCenterHorizontal)`.
  static const GravityIcon objectAlignCenterHorizontal = GravityIcon(0xf1cf);

  /// `Icon(GravityIcons.objectAlignCenterVertical)`.
  static const GravityIcon objectAlignCenterVertical = GravityIcon(0xf1ce);

  /// `Icon(GravityIcons.objectAlignJustifyHorizontal)`.
  static const GravityIcon objectAlignJustifyHorizontal = GravityIcon(0xf1cd);

  /// `Icon(GravityIcons.objectAlignJustifyVertical)`.
  static const GravityIcon objectAlignJustifyVertical = GravityIcon(0xf1cc);

  /// `Icon(GravityIcons.objectAlignLeft)`.
  static const GravityIcon objectAlignLeft = GravityIcon(0xf1cb);

  /// `Icon(GravityIcons.objectAlignRight)`.
  static const GravityIcon objectAlignRight = GravityIcon(0xf1ca);

  /// `Icon(GravityIcons.objectAlignTop)`.
  static const GravityIcon objectAlignTop = GravityIcon(0xf1c9);

  /// `Icon(GravityIcons.objectsAlignBottom)`.
  static const GravityIcon objectsAlignBottom = GravityIcon(0xf1c8);

  /// `Icon(GravityIcons.objectsAlignCenterHorizontal)`.
  static const GravityIcon objectsAlignCenterHorizontal = GravityIcon(0xf1c7);

  /// `Icon(GravityIcons.objectsAlignCenterVertical)`.
  static const GravityIcon objectsAlignCenterVertical = GravityIcon(0xf1c6);

  /// `Icon(GravityIcons.objectsAlignJustifyHorizontal)`.
  static const GravityIcon objectsAlignJustifyHorizontal = GravityIcon(0xf1c5);

  /// `Icon(GravityIcons.objectsAlignJustifyVertical)`.
  static const GravityIcon objectsAlignJustifyVertical = GravityIcon(0xf1c4);

  /// `Icon(GravityIcons.objectsAlignLeft)`.
  static const GravityIcon objectsAlignLeft = GravityIcon(0xf1c3);

  /// `Icon(GravityIcons.objectsAlignRight)`.
  static const GravityIcon objectsAlignRight = GravityIcon(0xf1c2);

  /// `Icon(GravityIcons.objectsAlignTop)`.
  static const GravityIcon objectsAlignTop = GravityIcon(0xf1c1);

  /// `Icon(GravityIcons.octagonXmark)`.
  static const GravityIcon octagonXmark = GravityIcon(0xf1c0);

  /// `Icon(GravityIcons.officeBadge)`.
  static const GravityIcon officeBadge = GravityIcon(0xf1bf);

  /// `Icon(GravityIcons.paintbrush)`.
  static const GravityIcon paintbrush = GravityIcon(0xf1be);

  /// `Icon(GravityIcons.palette)`.
  static const GravityIcon palette = GravityIcon(0xf1bd);

  /// `Icon(GravityIcons.paperPlane)`.
  static const GravityIcon paperPlane = GravityIcon(0xf1bc);

  /// `Icon(GravityIcons.paperclip)`.
  static const GravityIcon paperclip = GravityIcon(0xf1bb);

  /// `Icon(GravityIcons.passport)`.
  static const GravityIcon passport = GravityIcon(0xf1ba);

  /// `Icon(GravityIcons.pause)`.
  static const GravityIcon pause = GravityIcon(0xf1b8);

  /// `Icon(GravityIcons.pauseFill)`.
  static const GravityIcon pauseFill = GravityIcon(0xf1b9);

  /// `Icon(GravityIcons.pencil)`.
  static const GravityIcon pencil = GravityIcon(0xf1b5);

  /// `Icon(GravityIcons.pencilToLine)`.
  static const GravityIcon pencilToLine = GravityIcon(0xf1b7);

  /// `Icon(GravityIcons.pencilToSquare)`.
  static const GravityIcon pencilToSquare = GravityIcon(0xf1b6);

  /// `Icon(GravityIcons.percent)`.
  static const GravityIcon percent = GravityIcon(0xf1b4);

  /// `Icon(GravityIcons.person)`.
  static const GravityIcon person = GravityIcon(0xf1a9);

  /// `Icon(GravityIcons.personFill)`.
  static const GravityIcon personFill = GravityIcon(0xf1b3);

  /// `Icon(GravityIcons.personGear)`.
  static const GravityIcon personGear = GravityIcon(0xf1b2);

  /// `Icon(GravityIcons.personMagnifier)`.
  static const GravityIcon personMagnifier = GravityIcon(0xf1b1);

  /// `Icon(GravityIcons.personNutHex)`.
  static const GravityIcon personNutHex = GravityIcon(0xf1b0);

  /// `Icon(GravityIcons.personPencil)`.
  static const GravityIcon personPencil = GravityIcon(0xf1af);

  /// `Icon(GravityIcons.personPlanetEarth)`.
  static const GravityIcon personPlanetEarth = GravityIcon(0xf1ae);

  /// `Icon(GravityIcons.personPlus)`.
  static const GravityIcon personPlus = GravityIcon(0xf1ad);

  /// `Icon(GravityIcons.personSpeaker)`.
  static const GravityIcon personSpeaker = GravityIcon(0xf1ac);

  /// `Icon(GravityIcons.personWorker)`.
  static const GravityIcon personWorker = GravityIcon(0xf1ab);

  /// `Icon(GravityIcons.personXmark)`.
  static const GravityIcon personXmark = GravityIcon(0xf1aa);

  /// `Icon(GravityIcons.persons)`.
  static const GravityIcon persons = GravityIcon(0xf1a7);

  /// `Icon(GravityIcons.personsLock)`.
  static const GravityIcon personsLock = GravityIcon(0xf1a8);

  /// `Icon(GravityIcons.picture)`.
  static const GravityIcon picture = GravityIcon(0xf1a6);

  /// `Icon(GravityIcons.pill)`.
  static const GravityIcon pill = GravityIcon(0xf1a5);

  /// `Icon(GravityIcons.pin)`.
  static const GravityIcon pin = GravityIcon(0xf1a1);

  /// `Icon(GravityIcons.pinFill)`.
  static const GravityIcon pinFill = GravityIcon(0xf1a4);

  /// `Icon(GravityIcons.pinSlash)`.
  static const GravityIcon pinSlash = GravityIcon(0xf1a2);

  /// `Icon(GravityIcons.pinSlashFill)`.
  static const GravityIcon pinSlashFill = GravityIcon(0xf1a3);

  /// `Icon(GravityIcons.pipeline)`.
  static const GravityIcon pipeline = GravityIcon(0xf1a0);

  /// `Icon(GravityIcons.plane)`.
  static const GravityIcon plane = GravityIcon(0xf19e);

  /// `Icon(GravityIcons.planeFill)`.
  static const GravityIcon planeFill = GravityIcon(0xf19f);

  /// `Icon(GravityIcons.planetEarth)`.
  static const GravityIcon planetEarth = GravityIcon(0xf19d);

  /// `Icon(GravityIcons.play)`.
  static const GravityIcon play = GravityIcon(0xf19b);

  /// `Icon(GravityIcons.playFill)`.
  static const GravityIcon playFill = GravityIcon(0xf19c);

  /// `Icon(GravityIcons.plugConnection)`.
  static const GravityIcon plugConnection = GravityIcon(0xf19a);

  /// `Icon(GravityIcons.plugWire)`.
  static const GravityIcon plugWire = GravityIcon(0xf199);

  /// `Icon(GravityIcons.plus)`.
  static const GravityIcon plus = GravityIcon(0xf196);

  /// `Icon(GravityIcons.plusShape)`.
  static const GravityIcon plusShape = GravityIcon(0xf197);

  /// `Icon(GravityIcons.plusShapeFill)`.
  static const GravityIcon plusShapeFill = GravityIcon(0xf198);

  /// `Icon(GravityIcons.power)`.
  static const GravityIcon power = GravityIcon(0xf195);

  /// `Icon(GravityIcons.printer)`.
  static const GravityIcon printer = GravityIcon(0xf194);

  /// `Icon(GravityIcons.pulse)`.
  static const GravityIcon pulse = GravityIcon(0xf193);

  /// `Icon(GravityIcons.puzzle)`.
  static const GravityIcon puzzle = GravityIcon(0xf192);

  /// `Icon(GravityIcons.qrCode)`.
  static const GravityIcon qrCode = GravityIcon(0xf191);

  /// `Icon(GravityIcons.quoteClose)`.
  static const GravityIcon quoteClose = GravityIcon(0xf190);

  /// `Icon(GravityIcons.quoteOpen)`.
  static const GravityIcon quoteOpen = GravityIcon(0xf18f);

  /// `Icon(GravityIcons.receipt)`.
  static const GravityIcon receipt = GravityIcon(0xf18e);

  /// `Icon(GravityIcons.rectanglePulse)`.
  static const GravityIcon rectanglePulse = GravityIcon(0xf18d);

  /// `Icon(GravityIcons.rectangles4)`.
  static const GravityIcon rectangles4 = GravityIcon(0xf18c);

  /// `Icon(GravityIcons.rocket)`.
  static const GravityIcon rocket = GravityIcon(0xf18b);

  /// `Icon(GravityIcons.roundBrackets)`.
  static const GravityIcon roundBrackets = GravityIcon(0xf18a);

  /// `Icon(GravityIcons.route)`.
  static const GravityIcon route = GravityIcon(0xf189);

  /// `Icon(GravityIcons.sack)`.
  static const GravityIcon sack = GravityIcon(0xf188);

  /// `Icon(GravityIcons.scalesBalanced)`.
  static const GravityIcon scalesBalanced = GravityIcon(0xf187);

  /// `Icon(GravityIcons.scalesUnbalanced)`.
  static const GravityIcon scalesUnbalanced = GravityIcon(0xf186);

  /// `Icon(GravityIcons.scissors)`.
  static const GravityIcon scissors = GravityIcon(0xf185);

  /// `Icon(GravityIcons.sealCheck)`.
  static const GravityIcon sealCheck = GravityIcon(0xf184);

  /// `Icon(GravityIcons.sealPercent)`.
  static const GravityIcon sealPercent = GravityIcon(0xf183);

  /// `Icon(GravityIcons.server)`.
  static const GravityIcon server = GravityIcon(0xf182);

  /// `Icon(GravityIcons.shapes3)`.
  static const GravityIcon shapes3 = GravityIcon(0xf181);

  /// `Icon(GravityIcons.shapes4)`.
  static const GravityIcon shapes4 = GravityIcon(0xf180);

  /// `Icon(GravityIcons.shield)`.
  static const GravityIcon shield = GravityIcon(0xf17c);

  /// `Icon(GravityIcons.shieldCheck)`.
  static const GravityIcon shieldCheck = GravityIcon(0xf17f);

  /// `Icon(GravityIcons.shieldExclamation)`.
  static const GravityIcon shieldExclamation = GravityIcon(0xf17e);

  /// `Icon(GravityIcons.shieldKeyhole)`.
  static const GravityIcon shieldKeyhole = GravityIcon(0xf17d);

  /// `Icon(GravityIcons.shoppingBag)`.
  static const GravityIcon shoppingBag = GravityIcon(0xf17b);

  /// `Icon(GravityIcons.shoppingBasket)`.
  static const GravityIcon shoppingBasket = GravityIcon(0xf17a);

  /// `Icon(GravityIcons.shoppingCart)`.
  static const GravityIcon shoppingCart = GravityIcon(0xf179);

  /// `Icon(GravityIcons.shuffle)`.
  static const GravityIcon shuffle = GravityIcon(0xf178);

  /// `Icon(GravityIcons.signal)`.
  static const GravityIcon signal = GravityIcon(0xf177);

  /// `Icon(GravityIcons.skull)`.
  static const GravityIcon skull = GravityIcon(0xf176);

  /// `Icon(GravityIcons.sliders)`.
  static const GravityIcon sliders = GravityIcon(0xf174);

  /// `Icon(GravityIcons.slidersVertical)`.
  static const GravityIcon slidersVertical = GravityIcon(0xf175);

  /// `Icon(GravityIcons.smartphone)`.
  static const GravityIcon smartphone = GravityIcon(0xf173);

  /// `Icon(GravityIcons.snail)`.
  static const GravityIcon snail = GravityIcon(0xf172);

  /// `Icon(GravityIcons.snowflake)`.
  static const GravityIcon snowflake = GravityIcon(0xf171);

  /// `Icon(GravityIcons.sparkles)`.
  static const GravityIcon sparkles = GravityIcon(0xf16f);

  /// `Icon(GravityIcons.sparklesFill)`.
  static const GravityIcon sparklesFill = GravityIcon(0xf170);

  /// `Icon(GravityIcons.speedometer)`.
  static const GravityIcon speedometer = GravityIcon(0xf16e);

  /// `Icon(GravityIcons.sphere)`.
  static const GravityIcon sphere = GravityIcon(0xf16d);

  /// `Icon(GravityIcons.square)`.
  static const GravityIcon square = GravityIcon(0xf152);

  /// `Icon(GravityIcons.squareArticle)`.
  static const GravityIcon squareArticle = GravityIcon(0xf16c);

  /// `Icon(GravityIcons.squareBars)`.
  static const GravityIcon squareBars = GravityIcon(0xf16a);

  /// `Icon(GravityIcons.squareBarsVertical)`.
  static const GravityIcon squareBarsVertical = GravityIcon(0xf16b);

  /// `Icon(GravityIcons.squareBrackets)`.
  static const GravityIcon squareBrackets = GravityIcon(0xf167);

  /// `Icon(GravityIcons.squareBracketsBarsVertical)`.
  static const GravityIcon squareBracketsBarsVertical = GravityIcon(0xf169);

  /// `Icon(GravityIcons.squareBracketsLetterA)`.
  static const GravityIcon squareBracketsLetterA = GravityIcon(0xf168);

  /// `Icon(GravityIcons.squareChartBar)`.
  static const GravityIcon squareChartBar = GravityIcon(0xf166);

  /// `Icon(GravityIcons.squareChartColumn)`.
  static const GravityIcon squareChartColumn = GravityIcon(0xf165);

  /// `Icon(GravityIcons.squareCheck)`.
  static const GravityIcon squareCheck = GravityIcon(0xf164);

  /// `Icon(GravityIcons.squareDashed)`.
  static const GravityIcon squareDashed = GravityIcon(0xf15f);

  /// `Icon(GravityIcons.squareDashedCircle)`.
  static const GravityIcon squareDashedCircle = GravityIcon(0xf163);

  /// `Icon(GravityIcons.squareDashedLetterA)`.
  static const GravityIcon squareDashedLetterA = GravityIcon(0xf162);

  /// `Icon(GravityIcons.squareDashedLetterT)`.
  static const GravityIcon squareDashedLetterT = GravityIcon(0xf161);

  /// `Icon(GravityIcons.squareDashedText)`.
  static const GravityIcon squareDashedText = GravityIcon(0xf160);

  /// `Icon(GravityIcons.squareDot)`.
  static const GravityIcon squareDot = GravityIcon(0xf15e);

  /// `Icon(GravityIcons.squareExclamation)`.
  static const GravityIcon squareExclamation = GravityIcon(0xf15d);

  /// `Icon(GravityIcons.squareFill)`.
  static const GravityIcon squareFill = GravityIcon(0xf15c);

  /// `Icon(GravityIcons.squareHashtag)`.
  static const GravityIcon squareHashtag = GravityIcon(0xf15b);

  /// `Icon(GravityIcons.squareLetterP)`.
  static const GravityIcon squareLetterP = GravityIcon(0xf15a);

  /// `Icon(GravityIcons.squareLetterT)`.
  static const GravityIcon squareLetterT = GravityIcon(0xf159);

  /// `Icon(GravityIcons.squareLineHorizontal)`.
  static const GravityIcon squareLineHorizontal = GravityIcon(0xf158);

  /// `Icon(GravityIcons.squareLineVertical)`.
  static const GravityIcon squareLineVertical = GravityIcon(0xf157);

  /// `Icon(GravityIcons.squareListUl)`.
  static const GravityIcon squareListUl = GravityIcon(0xf156);

  /// `Icon(GravityIcons.squareMinus)`.
  static const GravityIcon squareMinus = GravityIcon(0xf155);

  /// `Icon(GravityIcons.squarePlus)`.
  static const GravityIcon squarePlus = GravityIcon(0xf154);

  /// `Icon(GravityIcons.squareXmark)`.
  static const GravityIcon squareXmark = GravityIcon(0xf153);

  /// `Icon(GravityIcons.star)`.
  static const GravityIcon star = GravityIcon(0xf150);

  /// `Icon(GravityIcons.starFill)`.
  static const GravityIcon starFill = GravityIcon(0xf151);

  /// `Icon(GravityIcons.stethoscope)`.
  static const GravityIcon stethoscope = GravityIcon(0xf14f);

  /// `Icon(GravityIcons.sticker)`.
  static const GravityIcon sticker = GravityIcon(0xf14e);

  /// `Icon(GravityIcons.stop)`.
  static const GravityIcon stop = GravityIcon(0xf14c);

  /// `Icon(GravityIcons.stopFill)`.
  static const GravityIcon stopFill = GravityIcon(0xf14d);

  /// `Icon(GravityIcons.stopwatch)`.
  static const GravityIcon stopwatch = GravityIcon(0xf14b);

  /// `Icon(GravityIcons.strikethrough)`.
  static const GravityIcon strikethrough = GravityIcon(0xf14a);

  /// `Icon(GravityIcons.suitcase)`.
  static const GravityIcon suitcase = GravityIcon(0xf149);

  /// `Icon(GravityIcons.sun)`.
  static const GravityIcon sun = GravityIcon(0xf148);

  /// `Icon(GravityIcons.superscript)`.
  static const GravityIcon superscript = GravityIcon(0xf147);

  /// `Icon(GravityIcons.tShirt)`.
  static const GravityIcon tShirt = GravityIcon(0xf146);

  /// `Icon(GravityIcons.tachometer)`.
  static const GravityIcon tachometer = GravityIcon(0xf145);

  /// `Icon(GravityIcons.tag)`.
  static const GravityIcon tag = GravityIcon(0xf142);

  /// `Icon(GravityIcons.tagDollar)`.
  static const GravityIcon tagDollar = GravityIcon(0xf144);

  /// `Icon(GravityIcons.tagRuble)`.
  static const GravityIcon tagRuble = GravityIcon(0xf143);

  /// `Icon(GravityIcons.tags)`.
  static const GravityIcon tags = GravityIcon(0xf141);

  /// `Icon(GravityIcons.target)`.
  static const GravityIcon target = GravityIcon(0xf13f);

  /// `Icon(GravityIcons.targetDart)`.
  static const GravityIcon targetDart = GravityIcon(0xf140);

  /// `Icon(GravityIcons.terminal)`.
  static const GravityIcon terminal = GravityIcon(0xf13d);

  /// `Icon(GravityIcons.terminalLine)`.
  static const GravityIcon terminalLine = GravityIcon(0xf13e);

  /// `Icon(GravityIcons.text)`.
  static const GravityIcon text = GravityIcon(0xf136);

  /// `Icon(GravityIcons.textAlignCenter)`.
  static const GravityIcon textAlignCenter = GravityIcon(0xf13c);

  /// `Icon(GravityIcons.textAlignJustify)`.
  static const GravityIcon textAlignJustify = GravityIcon(0xf13b);

  /// `Icon(GravityIcons.textAlignLeft)`.
  static const GravityIcon textAlignLeft = GravityIcon(0xf13a);

  /// `Icon(GravityIcons.textAlignRight)`.
  static const GravityIcon textAlignRight = GravityIcon(0xf139);

  /// `Icon(GravityIcons.textIndent)`.
  static const GravityIcon textIndent = GravityIcon(0xf138);

  /// `Icon(GravityIcons.textOutdent)`.
  static const GravityIcon textOutdent = GravityIcon(0xf137);

  /// `Icon(GravityIcons.thumbsDown)`.
  static const GravityIcon thumbsDown = GravityIcon(0xf134);

  /// `Icon(GravityIcons.thumbsDownFill)`.
  static const GravityIcon thumbsDownFill = GravityIcon(0xf135);

  /// `Icon(GravityIcons.thumbsUp)`.
  static const GravityIcon thumbsUp = GravityIcon(0xf131);

  /// `Icon(GravityIcons.thumbsUp2)`.
  static const GravityIcon thumbsUp2 = GravityIcon(0xf133);

  /// `Icon(GravityIcons.thumbsUpFill)`.
  static const GravityIcon thumbsUpFill = GravityIcon(0xf132);

  /// `Icon(GravityIcons.thunderbolt)`.
  static const GravityIcon thunderbolt = GravityIcon(0xf12f);

  /// `Icon(GravityIcons.thunderboltFill)`.
  static const GravityIcon thunderboltFill = GravityIcon(0xf130);

  /// `Icon(GravityIcons.ticket)`.
  static const GravityIcon ticket = GravityIcon(0xf12e);

  /// `Icon(GravityIcons.timeline)`.
  static const GravityIcon timeline = GravityIcon(0xf12d);

  /// `Icon(GravityIcons.timestamps)`.
  static const GravityIcon timestamps = GravityIcon(0xf12c);

  /// `Icon(GravityIcons.toggleOff)`.
  static const GravityIcon toggleOff = GravityIcon(0xf12b);

  /// `Icon(GravityIcons.toggleOn)`.
  static const GravityIcon toggleOn = GravityIcon(0xf12a);

  /// `Icon(GravityIcons.trafficLight)`.
  static const GravityIcon trafficLight = GravityIcon(0xf129);

  /// `Icon(GravityIcons.trapezoidLeftLineHorizontal)`.
  static const GravityIcon trapezoidLeftLineHorizontal = GravityIcon(0xf128);

  /// `Icon(GravityIcons.trapezoidUpLineVertical)`.
  static const GravityIcon trapezoidUpLineVertical = GravityIcon(0xf127);

  /// `Icon(GravityIcons.trashBin)`.
  static const GravityIcon trashBin = GravityIcon(0xf126);

  /// `Icon(GravityIcons.tray)`.
  static const GravityIcon tray = GravityIcon(0xf125);

  /// `Icon(GravityIcons.triangleDown)`.
  static const GravityIcon triangleDown = GravityIcon(0xf123);

  /// `Icon(GravityIcons.triangleDownFill)`.
  static const GravityIcon triangleDownFill = GravityIcon(0xf124);

  /// `Icon(GravityIcons.triangleExclamation)`.
  static const GravityIcon triangleExclamation = GravityIcon(0xf121);

  /// `Icon(GravityIcons.triangleExclamationFill)`.
  static const GravityIcon triangleExclamationFill = GravityIcon(0xf122);

  /// `Icon(GravityIcons.triangleLeft)`.
  static const GravityIcon triangleLeft = GravityIcon(0xf11f);

  /// `Icon(GravityIcons.triangleLeftFill)`.
  static const GravityIcon triangleLeftFill = GravityIcon(0xf120);

  /// `Icon(GravityIcons.triangleRight)`.
  static const GravityIcon triangleRight = GravityIcon(0xf11d);

  /// `Icon(GravityIcons.triangleRightFill)`.
  static const GravityIcon triangleRightFill = GravityIcon(0xf11e);

  /// `Icon(GravityIcons.triangleThunderbolt)`.
  static const GravityIcon triangleThunderbolt = GravityIcon(0xf11c);

  /// `Icon(GravityIcons.triangleUp)`.
  static const GravityIcon triangleUp = GravityIcon(0xf11a);

  /// `Icon(GravityIcons.triangleUpFill)`.
  static const GravityIcon triangleUpFill = GravityIcon(0xf11b);

  /// `Icon(GravityIcons.trolley)`.
  static const GravityIcon trolley = GravityIcon(0xf119);

  /// `Icon(GravityIcons.tv)`.
  static const GravityIcon tv = GravityIcon(0xf117);

  /// `Icon(GravityIcons.tvRetro)`.
  static const GravityIcon tvRetro = GravityIcon(0xf118);

  /// `Icon(GravityIcons.umbrella)`.
  static const GravityIcon umbrella = GravityIcon(0xf116);

  /// `Icon(GravityIcons.underline)`.
  static const GravityIcon underline = GravityIcon(0xf115);

  /// `Icon(GravityIcons.universalAccess)`.
  static const GravityIcon universalAccess = GravityIcon(0xf114);

  /// `Icon(GravityIcons.vault)`.
  static const GravityIcon vault = GravityIcon(0xf113);

  /// `Icon(GravityIcons.vectorCircle)`.
  static const GravityIcon vectorCircle = GravityIcon(0xf112);

  /// `Icon(GravityIcons.vectorSquare)`.
  static const GravityIcon vectorSquare = GravityIcon(0xf111);

  /// `Icon(GravityIcons.video)`.
  static const GravityIcon video = GravityIcon(0xf110);

  /// `Icon(GravityIcons.volume)`.
  static const GravityIcon volume = GravityIcon(0xf106);

  /// `Icon(GravityIcons.volumeFill)`.
  static const GravityIcon volumeFill = GravityIcon(0xf10f);

  /// `Icon(GravityIcons.volumeLow)`.
  static const GravityIcon volumeLow = GravityIcon(0xf10d);

  /// `Icon(GravityIcons.volumeLowFill)`.
  static const GravityIcon volumeLowFill = GravityIcon(0xf10e);

  /// `Icon(GravityIcons.volumeOff)`.
  static const GravityIcon volumeOff = GravityIcon(0xf10b);

  /// `Icon(GravityIcons.volumeOffFill)`.
  static const GravityIcon volumeOffFill = GravityIcon(0xf10c);

  /// `Icon(GravityIcons.volumeSlash)`.
  static const GravityIcon volumeSlash = GravityIcon(0xf109);

  /// `Icon(GravityIcons.volumeSlashFill)`.
  static const GravityIcon volumeSlashFill = GravityIcon(0xf10a);

  /// `Icon(GravityIcons.volumeXmark)`.
  static const GravityIcon volumeXmark = GravityIcon(0xf107);

  /// `Icon(GravityIcons.volumeXmarkFill)`.
  static const GravityIcon volumeXmarkFill = GravityIcon(0xf108);

  /// `Icon(GravityIcons.weightHanging)`.
  static const GravityIcon weightHanging = GravityIcon(0xf105);

  /// `Icon(GravityIcons.wrench)`.
  static const GravityIcon wrench = GravityIcon(0xf104);

  /// `Icon(GravityIcons.xmark)`.
  static const GravityIcon xmark = GravityIcon(0xf101);

  /// `Icon(GravityIcons.xmarkShape)`.
  static const GravityIcon xmarkShape = GravityIcon(0xf102);

  /// `Icon(GravityIcons.xmarkShapeFill)`.
  static const GravityIcon xmarkShapeFill = GravityIcon(0xf103);
}
